# tax_key = 0.0
zero_tax = [
    'Abaújalpár', 'Abaújlak', 'Acsád', 'Adorjánháza', 'Adorjás', 'Aggtelek', 'Almamellék', 'Almásháza',
    'Almáskeresztúr', 'Andrásfa', 'Annavölgy', 'Apácatorna', 'Aranyosgadány', 'Bakháza', 'Bakonyság', 'Balajt',
    'Baranyahídvég', 'Basal', 'Benk', 'Bezeréd', 'Bikács', 'Bocska', 'Bodonhely', 'Bogádmindszent', 'Bokor',
    'Botpalád', 'Botykapeterd', 'Bátorliget', 'Börzönce', 'Bükkmogyorósd', 'Cakóháza', 'Cirák', 'Csaholc',
    'Csebény', 'Csehbánya', 'Cserhátszentiván', 'Csokonyavisonta', 'Csomád', 'Császló', 'Csöde', 'Csögle',
    'Csővár', 'Cún', 'Daraboshegy', 'Drávapiski', 'Dubicsány', 'Dunaszentbenedek', 'Dámóc', 'Dénesfa', 'Edve',
    'Egeralja', 'Egyházasdengeleg', 'Fehértó', 'Feked', 'Felsőszenterzsébet', 'Felsőtold', 'Fony', 'Fülesd',
    'Füzér', 'Gacsály', 'Gadna', 'Gagyvendégi', 'Galvács', 'Garbolc', 'Garáb', 'Gemzse', 'Gyalóka', 'Gyulaháza',
    'Gyügye', 'Gyüre', 'Gyűrűs', 'Göncruszka', 'Hegyszentmárton', 'Hejce', 'Helesfa', 'Hercegkút', 'Hermánszeg',
    'Hernádbűd', 'Homokkomárom', 'Horváthertelend', 'Hosszúvíz', 'Husztót', 'Háromhuta', 'Ibafa', 'Irota',
    'Jágónak', 'Járdánháza', 'Kacorlak', 'Kallósd', 'Kaposszekcső', 'Kemeneskápolna', 'Kemse', 'Keménfa',
    'Kenéz', 'Kerecseny', 'Kisbabot', 'Kisbajom', 'Kisberzseny', 'Kisbárkány', 'Kisdér', 'Kisgörbő', 'Kishódos',
    'Kiskassa', 'Kisnamény', 'Kispalád', 'Kispirit', 'Kispáli', 'Kisrécse', 'Kistamási', 'Komlósd', 'Komlóska',
    'Korlát', 'Kovácsszénája', 'Kupa', 'Kutasó', 'Kántorjánosi', 'Kánó', 'Lad', 'Lasztonya', 'Lengyel',
    'Ligetfalva', 'Ládbesenyő', 'Maglóca', 'Magosliget', 'Magy', 'Magyaregregy', 'Magyarföld', 'Magyarnádalja',
    'Markotabödöge', 'Martonfa', 'Megyehíd', 'Megyer', 'Mesteri', 'Meszlen', 'Mike', 'Molvány', 'Monaj',
    'Mucsfa', 'Murarátka', 'Márfa', 'Márkháza', 'Méhtelek', 'Mérges', 'Nadap', 'Nagydobsza', 'Nagydém',
    'Nagyhódos', 'Nagykökényes', 'Nagypeterd', 'Nagypirit', 'Nagypáli', 'Nagyszokoly', 'Nagyvejke', 'Nagyváty',
    'Nemesborzova', 'Nemeshetés', 'Nemeskocs', 'Nemeskér', 'Nemesmedves', 'Nemespátró', 'Nyugotszenterzsébet',
    'Nyésta', 'Nyírcsászári', 'Nyírjákó', 'Nyírkáta', 'Nyírpilis', 'Padár', 'Pamuk', 'Pap', 'Pat',
    'Patapoklosi', 'Patca', 'Patosfa', 'Pereked', 'Pettend', 'Pinkamindszent', 'Porrog', 'Porrogszentkirály',
    'Porrogszentpál', 'Pécsdevecser', 'Pölöskefő', 'Rinyaújlak', 'Romonya', 'Rozsály', 'Rábacsécsény',
    'Rábaszentmiklós', 'Rábcakapi', 'Rápolt', 'Révleányvár', 'Sand', 'Semjénháza', 'Somogybükkösd',
    'Somogycsicsó', 'Somogysimonyi', 'Somogyszentpál', 'Somogyviszló', 'Sonkád', 'Surd', 'Szakony',
    'Szamosújlak', 'Szemenye', 'Szentjakabfa', 'Szin', 'Szinpetri', 'Szulimán', 'Szárász', 'Szőkéd', 'Sámod',
    'Sámsonháza', 'Sárszentmihály', 'Sénye', 'Tarjánpuszta', 'Tarnabod', 'Tengeri', 'Terem', 'Teresztenye',
    'Tilaj', 'Tiszamogyorós', 'Tisztaberek', 'Tornakápolna', 'Tápszentmiklós', 'Tényő', 'Tésa', 'Tésenfa',
    'Tófű', 'Tótszentgyörgy', 'Tömörd', 'Túrricse', 'Tüskevár', 'Und', 'Varbóc', 'Vasalja', 'Vekerd', 'Vezseny',
    'Viszló', 'Viszák', 'Vizslás', 'Vásárosbéc', 'Vásárosfalu', 'Vásárosmiske', 'Vékény', 'Vöckönd', 'Zabar',
    'Zajta', 'Zalaboldogfa', 'Zalaköveskút', 'Zalasárszeg', 'Zalaújlak', 'Zengővárkony', 'Závod', 'Áta',
    'Óbudavár', 'Ózdfalu', 'Újlengyel', 'Újlőrincfalva', 'Újsolt', 'Őr'
]

# All cities and taxes
tax_by_city = {
    'Pálfiszeg': '2.0', 'Tiszanána': '1.0', 'Milejszeg': '2.0', 'Csonkahegyhát': '2.0', 'Semjénháza': '0.0',
    'Komlódtótfalu': '2.0', 'Bodmér': '0.4', 'Sárkeresztúr': '2.0', 'Nagyhalász': '1.5', 'Égerszög': '0.5',
    'Vásárosnamény': '1.8', 'Szőlősardó': '1.2', 'Sajókápolna': '1.75', 'Perkupa': '1.5', 'Ráckeve': '2.0',
    'Alsónémedi': '1.9', 'Vállus': '2.0', 'Gyenesdiás': '2.0', 'Szakonyfalu': '1.4', 'Alsószölnök': '1.4',
    'Regenye': '1.0', 'Ócsárd': '2.0', 'Jászszentandrás': '1.5', 'Jászivány': '1.5', 'Tikos': '2.0',
    'Hollád': '2.0', 'Miháld': '2.0', 'Csapi': '2.0', 'Ártánd': '2.0', 'Biharkeresztes': '2.0',
    'Tárnokréti': '1.5', 'Dör': '1.6', 'Bősárkány': '1.5', 'Szirmabesenyő': '1.9', 'Mohács': '2.0',
    'Zebecke': '2.0', 'Zalavég': '2.0', 'Zalavár': '2.0', 'Zalaújlak': '0.0', 'Zalatárnok': '2.0',
    'Zalaszombatfa': '2.0', 'Zalaszentmihály': '1.8', 'Zalaszentmárton': '2.0', 'Zalaszentlőrinc': '1.8',
    'Zalaszentlászló': '1.0', 'Zalaszentjakab': '1.6', 'Zalaszentiván': '2.0', 'Zalaszentgyörgy': '2.0',
    'Zalaszentgrót': '2.0', 'Zalaszentbalázs': '1.5', 'Zalaszántó': '2.0', 'Zalaszabar': '2.0',
    'Zalasárszeg': '0.0', 'Zalamerenye': '2.0', 'Zalalövő': '1.6', 'Zalaköveskút': '0.0', 'Zalakomár': '2.0',
    'Zalakaros': '2.0', 'Zalaistvánd': '1.4', 'Zalaigrice': '2.0', 'Zalaháshágy': '1.0',
    'Zalaegerszeg': '2.0', 'Zalacséb': '2.0', 'Zalacsány': '2.0', 'Zalaboldogfa': '0.0', 'Zalabér': '2.0',
    'Zalabaksa': '2.0', 'Zalaapáti': '1.5', 'Zajk': '2.0', 'Vöckönd': '0.0', 'Vonyarcvashegy': '2.0',
    'Vindornyaszőlős': '2.0', 'Vindornyalak': '2.0', 'Vindornyafok': '2.0', 'Vaspör': '0.5',
    'Vasboldogasszony': '1.0', 'Várvölgy': '2.0', 'Várfölde': '1.8', 'Valkonya': '2.0', 'Újudvar': '1.5',
    'Türje': '2.0', 'Tótszerdahely': '2.0', 'Tótszentmárton': '1.3', 'Tornyiszentmiklós': '2.0',
    'Tormafölde': '1.5', 'Tófej': '2.0', 'Tilaj': '0.0', 'Teskánd': '2.0', 'Tekenye': '2.0',
    'Szilvágy': '2.0', 'Szijártóháza': '2.0', 'Szepetnek': '2.0', 'Szentpéterúr': '2.0',
    'Szentpéterfölde': '1.5', 'Szentmargitfalva': '1.0', 'Szentliszló': '1.2', 'Szentkozmadombja': '1.5',
    'Szentgyörgyvölgy': '1.4', 'Szentgyörgyvár': '2.0', 'Szécsisziget': '2.0', 'Szalapa': '1.7',
    'Sümegcsehi': '2.0', 'Surd': '0.0', 'Söjtör': '1.8', 'Sormás': '1.7', 'Sénye': '0.0', 'Sármellék': '2.0',
    'Sárhida': '2.0', 'Sand': '0.0', 'Salomvár': '2.0', 'Rigyác': '2.0', 'Rezi': '2.0', 'Resznek': '2.0',
    'Rédics': '2.0', 'Ramocsa': '2.0', 'Pusztaszentlászló': '2.0', 'Pusztamagyaród': '1.0',
    'Pusztaederics': '2.0', 'Pusztaapáti': '2.0', 'Pötréte': '2.0', 'Pördefölde': '1.0', 'Pölöskefő': '0.0',
    'Pölöske': '1.8', 'Pórszombat': '2.0', 'Pókaszepetk': '1.6', 'Petrivente': '0.8',
    'Petrikeresztúr': '2.0', 'Pethőhenye': '1.8', 'Pat': '0.0', 'Pakod': '2.0', 'Páka': '1.4',
    'Padár': '0.0', 'Pacsa': '2.0', 'Ozmánbük': '2.0', 'Ortaháza': '2.0', 'Orosztony': '1.0',
    'Ormándlak': '2.0', 'Orbányosfa': '2.0', 'Oltárc': '1.2', 'Óhíd': '1.7', 'Nova': '2.0',
    'Németfalu': '1.0', 'Nemesszentandrás': '1.5', 'Nemessándorháza': '2.0', 'Nemesrádó': '2.0',
    'Nemespátró': '0.0', 'Nemesnép': '1.5', 'Nemeshetés': '0.0', 'Nemesbük': '0.5', 'Nemesapáti': '2.0',
    'Nagyrécse': '1.0', 'Nagyrada': '1.5', 'Nagypáli': '0.0', 'Nagylengyel': '2.0', 'Nagykutas': '2.0',
    'Nagykapornak': '2.0', 'Nagykanizsa': '2.0', 'Nagygörbő': '1.0', 'Nagybakónak': '2.0',
    'Muraszemenye': '2.0', 'Murarátka': '0.0', 'Murakeresztúr': '2.0', 'Molnári': '2.0', 'Misefa': '1.0',
    'Mikekarácsonyfa': '2.0', 'Mihályfa': '2.0', 'Márokföld': '2.0', 'Maróc': '2.0',
    'Magyarszerdahely': '2.0', 'Magyarszentmiklós': '2.0', 'Magyarföld': '0.0', 'Lovászi': '2.0',
    'Liszó': '2.0', 'Lispeszentadorján': '2.0', 'Ligetfalva': '0.0', 'Lickóvadamos': '2.0', 'Letenye': '2.0',
    'Lenti': '2.0', 'Lendvajakabfa': '2.0', 'Lendvadedes': '2.0', 'Lasztonya': '0.0', 'Lakhegy': '1.0',
    'Külsősárd': '2.0', 'Kustánszeg': '2.0', 'Kozmadombja': '1.0', 'Kissziget': '1.5', 'Kisvásárhely': '1.0',
    'Kistolmács': '1.5', 'Kisrécse': '0.0', 'Kispáli': '0.0', 'Kiskutas': '2.0', 'Kisgörbő': '0.0',
    'Kiscsehi': '2.0', 'Kisbucsa': '1.0', 'Kilimán': '2.0', 'Keszthely': '2.0', 'Kerkateskánd': '2.0',
    'Kerkaszentkirály': '2.0', 'Kerkakutas': '1.0', 'Kerkafalva': '1.0', 'Kerkabarabás': '2.0',
    'Kerecseny': '0.0', 'Keménfa': '0.0', 'Kemendollár': '1.4', 'Kehidakustány': '2.0', 'Kávás': '2.0',
    'Karmacs': '2.0', 'Kányavár': '2.0', 'Kálócfa': '2.0', 'Kallósd': '0.0', 'Kacorlak': '0.0',
    'Iklódbördőce': '1.5', 'Iborfia': '2.0', 'Hottó': '2.0', 'Hosszúvölgy': '2.0', 'Homokkomárom': '0.0',
    'Hévíz': '2.0', 'Hernyék': '1.5', 'Hahót': '1.8', 'Hagyárosbörönd': '1.6', 'Gyűrűs': '0.0',
    'Gutorfölde': '2.0', 'Gősfa': '1.0', 'Gosztola': '1.0', 'Gombosszeg': '2.0', 'Gétye': '1.5',
    'Gelsesziget': '1.0', 'Gelse': '2.0', 'Gellénháza': '2.0', 'Garabonc': '1.0', 'Galambok': '1.8',
    'Gáborjánháza': '2.0', 'Fűzvölgy': '2.0', 'Fityeház': '2.0', 'Felsőszenterzsébet': '0.0',
    'Felsőrajk': '2.0', 'Felsőpáhok': '2.0', 'Esztergályhorváti': '1.0', 'Eszteregnye': '1.8',
    'Egervár': '1.5', 'Egeraracsa': '1.5', 'Dötk': '1.0', 'Döbröce': '1.0', 'Dobronhegy': '2.0',
    'Dobri': '1.6', 'Dióskál': '1.5', 'Csörnyeföld': '2.0', 'Csömödér': '1.5', 'Csöde': '0.0',
    'Csesztreg': '2.0', 'Csertalakos': '2.0', 'Cserszegtomaj': '2.0', 'Csatár': '2.0', 'Bucsuta': '2.0',
    'Búcsúszentlászló': '1.5', 'Börzönce': '0.0', 'Bödeháza': '2.0', 'Böde': '2.0', 'Borsfa': '1.5',
    'Boncodfölde': '2.0', 'Bókaháza': '0.5', 'Bocska': '0.0', 'Bocfölde': '2.0', 'Bezeréd': '0.0',
    'Belsősárd': '2.0', 'Belezna': '2.0', 'Becsvölgye': '2.0', 'Becsehely': '1.4', 'Bázakerettye': '2.0',
    'Batyk': '2.0', 'Barlahida': '2.0', 'Bánokszentgyörgy': '2.0', 'Balatonmagyaród': '2.0',
    'Balatongyörök': '1.5', 'Baktüttös': '2.0', 'Bak': '2.0', 'Bagod': '1.8', 'Baglad': '2.0',
    'Babosdöbréte': '2.0', 'Alsószenterzsébet': '1.4', 'Alsórajk': '2.0', 'Alsópáhok': '2.0',
    'Alsónemesapáti': '2.0', 'Almásháza': '0.0', 'Alibánfa': '2.0', 'Zirc': '2.0', 'Zánka': '1.9',
    'Zalaszegvár': '2.0', 'Zalameggyes': '2.0', 'Zalahaláp': '2.0', 'Zalagyömörő': '1.5', 'Zalaerdőd': '2.0',
    'Vöröstó': '2.0', 'Vinár': '2.0', 'Vilonya': '2.0', 'Vigántpetend': '2.0', 'Vid': '2.0',
    'Veszprémgalsa': '2.0', 'Veszprémfajsz': '2.0', 'Veszprém': '2.0', 'Vászoly': '1.7', 'Vaszar': '2.0',
    'Várpalota': '2.0', 'Városlőd': '1.5', 'Várkesző': '2.0', 'Vanyola': '1.8', 'Uzsa': '2.0',
    'Úrkút': '2.0', 'Ukk': '2.0', 'Ugod': '2.0', 'Tüskevár': '0.0', 'Tótvázsony': '1.8', 'Tihany': '2.0',
    'Tés': '2.0', 'Tapolca': '2.0', 'Taliándörögd': '1.8', 'Takácsi': '2.0', 'Tagyon': '1.0', 'Szőc': '2.0',
    'Szigliget': '2.0', 'Szentkirályszabadja': '1.8', 'Szentjakabfa': '0.0', 'Szentimrefalva': '2.0',
    'Szentgál': '1.5', 'Szentbékkálla': '1.0', 'Szentantalfa': '2.0', 'Szápár': '0.6', 'Sümegprága': '2.0',
    'Sümeg': '2.0', 'Somlóvecse': '2.0', 'Somlóvásárhely': '2.0', 'Somlószőlős': '1.5', 'Somlójenő': '2.0',
    'Sóly': '1.0', 'Sáska': '2.0', 'Salföld': '1.5', 'Rigács': '1.5', 'Révfülöp': '1.9', 'Raposka': '2.0',
    'Pusztamiske': '2.0', 'Pula': '2.0', 'Porva': '1.8', 'Pétfürdő': '2.0', 'Pénzesgyőr': '2.0',
    'Pécsely': '1.6', 'Papkeszi': '2.0', 'Pápateszér': '2.0', 'Pápasalamon': '2.0', 'Pápakovácsi': '2.0',
    'Pápadereske': '2.0', 'Pápa': '2.0', 'Paloznak': '1.8', 'Öskü': '2.0', 'Ősi': '2.0', 'Örvényes': '2.0',
    'Öcs': '1.8', 'Oroszi': '1.7', 'Olaszfalu': '2.0', 'Óbudavár': '0.0', 'Nyirád': '2.0', 'Nyárád': '2.0',
    'Noszlop': '2.0', 'Nóráp': '1.0', 'Németbánya': '1.5', 'Nemesszalók': '2.0', 'Nemesvita': '1.5',
    'Nemesvámos': '2.0', 'Nemeshany': '2.0', 'Nemesgulács': '2.0', 'Nemesgörzsöny': '2.0',
    'Nagyvázsony': '2.0', 'Nagytevel': '2.0', 'Nagypirit': '0.0', 'Nagygyimót': '2.0',
    'Nagyesztergár': '2.0', 'Nagydém': '0.0', 'Nagyalásony': '2.0', 'Nagyacsád': '2.0', 'Monoszló': '1.8',
    'Monostorapáti': '2.0', 'Mindszentkálla': '2.0', 'Mihályháza': '2.0', 'Mezőlak': '2.0',
    'Mencshely': '1.0', 'Megyer': '0.0', 'Márkó': '1.9', 'Marcaltő': '2.0', 'Marcalgergelyi': '2.0',
    'Malomsok': '2.0', 'Magyarpolány': '2.0', 'Magyargencs': '1.0', 'Lovászpatona': '1.8', 'Lovas': '1.7',
    'Lókút': '1.8', 'Litér': '2.0', 'Lesencetomaj': '2.0', 'Lesenceistvánd': '2.0', 'Lesencefalu': '1.4',
    'Küngös': '2.0', 'Külsővat': '2.0', 'Kup': '1.7', 'Köveskál': '1.0', 'Kővágóörs': '1.5',
    'Kolontár': '2.0', 'Kisszőlős': '2.0', 'Kispirit': '0.0', 'Kislőd': '2.0', 'Kiscsősz': '1.0',
    'Kisberzseny': '0.0', 'Kisapáti': '2.0', 'Királyszentistván': '2.0', 'Kerta': '1.7',
    'Kemenesszentpéter': '1.0', 'Kemeneshőgyész': '1.0', 'Kékkút': '2.0', 'Karakószörcsök': '2.0',
    'Káptalantóti': '1.7', 'Káptalanfa': '0.5', 'Kapolcs': '1.7', 'Kamond': '1.0', 'Jásd': '2.0',
    'Iszkáz': '2.0', 'Hosztót': '2.0', 'Homokbödöge': '2.0', 'Hidegkút': '0.8', 'Hetyefő': '2.0',
    'Herend': '2.0', 'Hegymagas': '1.2', 'Hegyesd': '2.0', 'Hárskút': '1.5', 'Halimba': '2.0',
    'Hajmáskér': '1.5', 'Gyulakeszi': '1.0', 'Gyepükaján': '2.0', 'Gógánfa': '2.0', 'Gic': '2.0',
    'Gecse': '1.7', 'Ganna': '0.5', 'Felsőörs': '1.9', 'Farkasgyepű': '2.0', 'Eplény': '2.0',
    'Egyházaskesző': '2.0', 'Egeralja': '0.0', 'Dudar': '2.0', 'Dörgicse': '1.4', 'Döbrönte': '0.5',
    'Doba': '1.5', 'Devecser': '2.0', 'Dáka': '2.0', 'Dabrony': '2.0', 'Dabronc': '2.0', 'Csögle': '0.0',
    'Csót': '2.0', 'Csopak': '2.0', 'Csetény': '1.8', 'Csesznek': '2.0', 'Csehbánya': '0.0', 'Csajág': '2.0',
    'Csabrendek': '2.0', 'Borzavár': '2.0', 'Borszörcsök': '2.0', 'Bodorfa': '2.0', 'Berhida': '2.0',
    'Békás': '2.0', 'Béb': '2.0', 'Bazsi': '2.0', 'Barnag': '1.0', 'Bánd': '1.4', 'Balatonudvari': '2.0',
    'Balatonszőlős': '1.6', 'Balatonszepezd': '2.0', 'Balatonrendes': '1.4', 'Balatonkenese': '1.9',
    'Balatonhenye': '1.0', 'Balatonfűzfő': '2.0', 'Balatonfüred': '2.0', 'Balatonfőkajár': '1.8',
    'Balatonederics': '1.8', 'Balatoncsicsó': '1.5', 'Balatonalmádi': '2.0', 'Balatonakarattya': '1.5',
    'Balatonakali': '2.0', 'Bakonytamási': '2.0', 'Bakonyszücs': '2.0', 'Bakonyszentkirály': '2.0',
    'Bakonyszentiván': '1.0', 'Bakonyság': '0.0', 'Bakonypölöske': '1.7', 'Bakonyoszlop': '2.0',
    'Bakonynána': '1.5', 'Bakonykoppány': '1.0', 'Bakonyjákó': '2.0', 'Bakonybél': '1.7',
    'Badacsonytördemic': '2.0', 'Badacsonytomaj': '2.0', 'Aszófő': '1.6', 'Apácatorna': '0.0',
    'Alsóörs': '1.9', 'Ajka': '2.0', 'Adorjánháza': '0.0', 'Adásztevel': '2.0', 'Ábrahámhegy': '1.7',
    'Zsennye': '1.6', 'Zsédeny': '2.0', 'Vönöck': '1.5', 'Viszák': '0.0', 'Vép': '2.0', 'Velemér': '2.0',
    'Velem': '1.0', 'Vát': '1.5', 'Vasszilvágy': '1.3', 'Vasszentmihály': '2.0', 'Vasszécseny': '1.4',
    'Vasvár': '2.0', 'Vassurány': '1.8', 'Vaskeresztes': '1.4', 'Vashosszúfalu': '1.5', 'Vasegerszeg': '1.8',
    'Vasasszonyfa': '1.8', 'Vásárosmiske': '0.0', 'Vasalja': '0.0', 'Vámoscsalád': '2.0',
    'Uraiújfalu': '2.0', 'Tömörd': '0.0', 'Torony': '1.5', 'Tormásliget': '2.0', 'Tompaládony': '2.0',
    'Tokorcs': '1.5', 'Telekes': '0.5', 'Táplánszentkereszt': '2.0', 'Tanakajd': '2.0', 'Szőce': '2.0',
    'Szombathely': '2.0', 'Szergény': '1.4', 'Szentpéterfa': '1.4', 'Szentgotthárd': '2.0',
    'Szemenye': '0.0', 'Szeleste': '1.0', 'Szatta': '1.5', 'Szarvaskend': '1.4', 'Szalafő': '1.4',
    'Szaknyér': '1.0', 'Söpte': '1.8', 'Sótony': '2.0', 'Sorokpolány': '2.0', 'Sorkikápolna': '2.0',
    'Sorkifalud': '1.7', 'Sitke': '1.0', 'Simaság': '2.0', 'Sé': '1.9', 'Sárvár': '2.0', 'Sárfimizdó': '1.5',
    'Salköveskút': '1.8', 'Sajtoskál': '2.0', 'Rum': '1.8', 'Rönök': '1.4', 'Répceszentgyörgy': '1.0',
    'Répcelak': '2.0', 'Rátót': '2.0', 'Rádóckölked': '1.7', 'Rábatöttös': '1.0', 'Rábapaty': '1.75',
    'Rábahídvég': '2.0', 'Rábagyarmat': '2.0', 'Püspökmolnári': '2.0', 'Pusztacsó': '1.8', 'Pósfa': '2.0',
    'Porpác': '1.0', 'Pornóapáti': '1.7', 'Pinkamindszent': '0.0', 'Petőmihályfa': '2.0', 'Peresznye': '1.7',
    'Perenye': '1.6', 'Pecöl': '1.0', 'Pápoc': '2.0', 'Pankasz': '1.0', 'Pácsony': '2.0',
    'Őriszentpéter': '2.0', 'Őrimagyarósd': '2.0', 'Ölbő': '2.0', 'Oszkó': '1.6', 'Ostffyasszonyfa': '2.0',
    'Orfalu': '1.0', 'Ólmod': '1.0', 'Olaszfa': '1.6', 'Nyőgér': '2.0', 'Nick': '2.0',
    'Nemesrempehollós': '2.0', 'Nemesmedves': '0.0', 'Nemesládony': '0.5', 'Nemeskolta': '1.7',
    'Nemeskocs': '0.0', 'Nemeskeresztúr': '2.0', 'Nemescsó': '1.5', 'Nemesbőd': '1.2', 'Narda': '1.6',
    'Nárai': '2.0', 'Nagytilaj': '1.5', 'Nagysimonyi': '1.5', 'Nagyrákos': '1.2', 'Nagymizdó': '1.5',
    'Nagykölked': '2.0', 'Nagygeresd': '2.0', 'Nádasd': '2.0', 'Molnaszecsőd': '2.0', 'Mikosszéplak': '1.5',
    'Meszlen': '0.0', 'Mesteri': '0.0', 'Mesterháza': '1.0', 'Mersevát': '1.5', 'Meggyeskovácsi': '2.0',
    'Megyehíd': '0.0', 'Magyarszombatfa': '2.0', 'Magyarszecsőd': '2.0', 'Magyarnádalja': '0.0',
    'Magyarlak': '2.0', 'Lukácsháza': '1.9', 'Lócs': '1.0', 'Kőszegszerdahely': '2.0', 'Kőszegpaty': '1.5',
    'Kőszegdoroszló': '2.0', 'Kőszeg': '2.0', 'Körmend': '2.0', 'Köcsk': '1.5', 'Kondorfa': '2.0',
    'Kiszsidány': '1.0', 'Kisunyom': '2.0', 'Kissomlyó': '2.0', 'Kisrákos': '1.0', 'Kétvölgy': '1.6',
    'Kerkáskápolna': '1.5', 'Kercaszomor': '2.0', 'Kenyeri': '1.0', 'Kenéz': '0.0', 'Kemestaródfa': '1.5',
    'Kemenesszentmárton': '1.5', 'Kemenessömjén': '1.0', 'Kemenespálfa': '1.5', 'Kemenesmihályfa': '2.0',
    'Kemenesmagasi': '1.4', 'Kemeneskápolna': '0.0', 'Keléd': '2.0', 'Katafa': '1.0', 'Karakó': '1.5',
    'Kám': '2.0', 'Káld': '2.0', 'Jánosháza': '2.0', 'Jákfa': '2.0', 'Ják': '2.0', 'Ivánc': '1.6',
    'Ispánk': '2.0', 'Iklanberény': '1.8', 'Ikervár': '2.0', 'Hosszúpereszteg': '1.5',
    'Horvátzsidány': '2.0', 'Horvátlövő': '1.7', 'Hegyhátszentpéter': '1.0', 'Hegyhátszentmárton': '2.0',
    'Hegyhátszentjakab': '2.0', 'Hegyhátsál': '2.0', 'Hegyháthodász': '2.0', 'Hegyfalu': '2.0',
    'Harasztifalu': '2.0', 'Halogy': '2.0', 'Halastó': '1.0', 'Győrvár': '2.0', 'Gyöngyösfalu': '1.9',
    'Gyanógeregye': '1.7', 'Gór': '1.5', 'Gersekarát': '1.5', 'Gérce': '1.5', 'Gencsapáti': '1.9',
    'Gasztony': '2.0', 'Felsőszölnök': '1.4', 'Felsőmarác': '0.5', 'Felsőjánosfa': '1.5',
    'Felsőcsatár': '1.8', 'Egyházasrádóc': '2.0', 'Egyházashollós': '1.8', 'Egyházashetye': '1.4',
    'Egervölgy': '2.0', 'Duka': '1.5', 'Döröske': '2.0', 'Döbörhegy': '1.5', 'Dozmat': '1.0',
    'Daraboshegy': '0.0', 'Csörötnek': '1.5', 'Csönge': '2.0', 'Csipkerek': '1.8', 'Csepreg': '2.0',
    'Csénye': '2.0', 'Csempeszkopács': '1.5', 'Csehimindszent': '2.0', 'Csehi': '1.8', 'Csánig': '2.0',
    'Csákánydoroszló': '1.3', 'Chernelházadamonya': '2.0', 'Celldömölk': '2.0', 'Cák': '2.0', 'Bük': '2.0',
    'Bucsu': '1.8', 'Bögöte': '1.6', 'Bögöt': '2.0', 'Bő': '2.0', 'Bozsok': '1.0', 'Bozzai': '2.0',
    'Borgáta': '0.8', 'Boba': '2.0', 'Bérbaltavár': '1.5', 'Bejcgyertyános': '2.0', 'Balogunyom': '1.8',
    'Bajánsenye': '2.0', 'Apátistvánfalva': '1.0', 'Andrásfa': '0.0', 'Alsóújlak': '1.8', 'Acsád': '0.0',
    'Zomba': '1.8', 'Závod': '0.0', 'Varsád': '1.5', 'Várong': '2.0', 'Várdomb': '2.0', 'Váralja': '1.4',
    'Újireg': '1.5', 'Udvari': '1.5', 'Tolnanémedi': '1.0', 'Tolna': '2.0', 'Tevel': '1.0',
    'Tengelic': '2.0', 'Tamási': '2.0', 'Szekszárd': '2.0', 'Szedres': '2.0', 'Szárazd': '1.5',
    'Szálka': '1.5', 'Szakcs': '1.5', 'Szakály': '1.0', 'Szakadát': '1.5', 'Sióagárd': '2.0',
    'Simontornya': '1.9', 'Sárszentlőrinc': '2.0', 'Sárpilis': '2.0', 'Regöly': '2.0', 'Pusztahencse': '1.5',
    'Pörböly': '2.0', 'Pincehely': '1.9', 'Pári': '1.5', 'Pálfa': '1.7', 'Paks': '2.0', 'Őcsény': '2.0',
    'Ozora': '2.0', 'Németkér': '1.2', 'Nak': '2.0', 'Nagyvejke': '0.0', 'Nagyszokoly': '0.0',
    'Nagyszékely': '1.5', 'Nagymányok': '1.3', 'Nagykónyi': '2.0', 'Nagydorog': '1.7', 'Murga': '2.0',
    'Mucsi': '2.0', 'Mucsfa': '0.0', 'Mőcsény': '2.0', 'Mórágy': '1.5', 'Miszla': '1.5', 'Medina': '2.0',
    'Magyarkeszi': '2.0', 'Madocsa': '2.0', 'Lengyel': '0.0', 'Lápafő': '2.0', 'Kurd': '1.8',
    'Kölesd': '1.0', 'Koppányszántó': '2.0', 'Kocsola': '1.7', 'Kisszékely': '1.6', 'Kisvejke': '2.0',
    'Kistormás': '1.0', 'Kismányok': '2.0', 'Kisdorog': '2.0', 'Kéty': '1.4', 'Keszőhidegkút': '2.0',
    'Kaposszekcső': '0.0', 'Kapospula': '1.7', 'Kalaznó': '1.0', 'Kakasd': '2.0', 'Kajdacs': '1.2',
    'Jágónak': '0.0', 'Izmény': '2.0', 'Iregszemcse': '2.0', 'Hőgyész': '1.7', 'Harc': '2.0',
    'Gyulaj': '2.0', 'Györköny': '1.4', 'Györe': '2.0', 'Gyönk': '1.5', 'Grábóc': '2.0', 'Gerjen': '2.0',
    'Fürged': '2.0', 'Felsőnyék': '1.0', 'Felsőnána': '1.4', 'Fadd': '1.8', 'Fácánkert': '2.0',
    'Értény': '1.0', 'Dúzs': '1.0', 'Dunaszentgyörgy': '2.0', 'Dunaföldvár': '2.0', 'Döbrököz': '2.0',
    'Dombóvár': '2.0', 'Diósberény': '1.5', 'Decs': '2.0', 'Dalmand': '2.0', 'Csikóstőttős': '1.4',
    'Csibrák': '1.1', 'Cikó': '2.0', 'Bölcske': '2.0', 'Bonyhádvarasd': '1.5', 'Bonyhád': '2.0',
    'Bogyiszló': '2.0', 'Bikács': '0.0', 'Belecska': '2.0', 'Bátaszék': '2.0', 'Bátaapáti': '2.0',
    'Báta': '2.0', 'Attala': '1.7', 'Aparhant': '2.0', 'Alsónyék': '2.0', 'Alsónána': '2.0',
    'Zagyvarékas': '1.7', 'Vezseny': '0.0', 'Újszász': '2.0', 'Túrkeve': '2.0', 'Törökszentmiklós': '2.0',
    'Tószeg': '1.8', 'Tomajmonostora': '1.0', 'Tiszavárkony': '1.8', 'Tiszatenyő': '1.4',
    'Tiszaszőlős': '2.0', 'Tiszaszentimre': '2.0', 'Tiszasüly': '2.0', 'Tiszasas': '1.5', 'Tiszaroff': '1.5',
    'Tiszapüspöki': '1.0', 'Tiszaörs': '2.0', 'Tiszakürt': '2.0', 'Tiszajenő': '1.6', 'Tiszainoka': '2.0',
    'Tiszaigar': '2.0', 'Tiszagyenda': '1.0', 'Tiszafüred': '2.0', 'Tiszaföldvár': '2.0',
    'Tiszaderzs': '1.0', 'Tiszabura': '2.0', 'Tiszabő': '1.5', 'Szolnok': '2.0', 'Szelevény': '2.0',
    'Szászberek': '2.0', 'Szajol': '2.0', 'Rákócziújfalu': '2.0', 'Rákóczifalva': '2.0',
    'Pusztamonostor': '1.8', 'Örményes': '1.7', 'Öcsöd': '2.0', 'Nagyrév': '2.0', 'Nagykörű': '2.0',
    'Nagyiván': '1.4', 'Mezőtúr': '2.0', 'Mezőhék': '1.8', 'Mesterszállás': '2.0', 'Martfű': '2.0',
    'Kunszentmárton': '2.0', 'Kunmadaras': '2.0', 'Kunhegyes': '2.0', 'Kuncsorba': '1.8', 'Kőtelek': '2.0',
    'Kisújszállás': '2.0', 'Kétpó': '2.0', 'Kengyel': '2.0', 'Kenderes': '2.0', 'Karcag': '2.0',
    'Jásztelek': '1.8', 'Jászladány': '2.0', 'Jászkisér': '2.0', 'Jászjákóhalma': '2.0',
    'Jászfényszaru': '1.4', 'Jászfelsőszentgyörgy': '1.4', 'Jászdózsa': '2.0', 'Jászboldogháza': '1.8',
    'Jászberény': '1.9', 'Jászárokszállás': '2.0', 'Jászapáti': '2.0', 'Jászalsószentgyörgy': '2.0',
    'Jászágó': '2.0', 'Jánoshida': '2.0', 'Hunyadfalva': '2.0', 'Fegyvernek': '1.7', 'Cserkeszőlő': '1.0',
    'Csépa': '2.0', 'Csataszög': '2.0', 'Cibakháza': '2.0', 'Besenyszög': '2.0', 'Berekfürdő': '2.0',
    'Alattyán': '1.8', 'Abádszalók': '2.0', 'Zsurk': '2.0', 'Zsarolyán': '2.0', 'Zajta': '0.0',
    'Záhony': '2.0', 'Vasmegyer': '1.4', 'Vámosoroszi': '2.0', 'Vámosatya': '1.4', 'Vállaj': '1.3',
    'Vaja': '2.0', 'Uszka': '2.0', 'Ura': '1.2', 'Újkenéz': '1.5', 'Újfehértó': '2.0', 'Újdombrád': '1.6',
    'Tyukod': '1.4', 'Tuzsér': '2.0', 'Túrricse': '0.0', 'Túristvándi': '1.0', 'Tunyogmatolcs': '1.25',
    'Tornyospálca': '1.7', 'Tivadar': '2.0', 'Tisztaberek': '0.0', 'Tiszavid': '1.5', 'Tiszavasvári': '1.4',
    'Tiszatelek': '1.0', 'Tiszaszentmárton': '2.0', 'Tiszaszalka': '1.4', 'Tiszarád': '1.5',
    'Tiszanagyfalu': '1.7', 'Tiszamogyorós': '0.0', 'Tiszalök': '1.5', 'Tiszakóród': '1.5',
    'Tiszakerecseny': '1.4', 'Tiszakanyár': '2.0', 'Tiszaeszlár': '2.0', 'Tiszadob': '1.5',
    'Tiszadada': '1.5', 'Tiszacsécse': '1.5', 'Tiszabezdéd': '2.0', 'Tiszabercel': '1.4', 'Tiszabecs': '2.0',
    'Tiszaadony': '1.4', 'Timár': '1.8', 'Tiborszállás': '2.0', 'Terem': '0.0', 'Tarpa': '1.2',
    'Tákos': '1.5', 'Szorgalmatos': '1.4', 'Székely': '2.0', 'Szatmárcseke': '1.4', 'Szamosszeg': '2.0',
    'Szamosújlak': '0.0', 'Szamostatárfalva': '2.0', 'Szamossályi': '1.5', 'Szamoskér': '0.5',
    'Szamosbecs': '2.0', 'Szamosangyalos': '2.0', 'Szakoly': '2.0', 'Szabolcsveresmart': '1.5',
    'Szabolcsbáka': '1.4', 'Szabolcs': '1.6', 'Sonkád': '0.0', 'Sényő': '2.0', 'Rozsály': '0.0',
    'Rohod': '1.5', 'Rétközberencs': '1.8', 'Rápolt': '0.0', 'Ramocsaháza': '2.0', 'Rakamaz': '2.0',
    'Pusztadobos': '2.0', 'Porcsalma': '1.4', 'Pócspetri': '1.5', 'Piricse': '0.5', 'Petneháza': '2.0',
    'Penyige': '1.5', 'Penészlek': '1.0', 'Pátyod': '2.0', 'Pátroha': '1.8', 'Paszab': '1.8', 'Papos': '2.0',
    'Pap': '0.0', 'Panyola': '1.4', 'Őr': '0.0', 'Ömböly': '1.3', 'Ököritófülpös': '2.0', 'Ópályi': '1.5',
    'Olcsvaapáti': '1.0', 'Olcsva': '1.0', 'Ófehértó': '2.0', 'Nyírvasvári': '1.5', 'Nyírtura': '1.5',
    'Nyírtét': '2.0', 'Nyírtelek': '2.0', 'Nyírtass': '1.8', 'Nyírpilis': '0.0', 'Nyírpazony': '2.0',
    'Nyírparasznya': '2.0', 'Nyírmihálydi': '1.0', 'Nyírmeggyes': '1.0', 'Nyírmada': '1.6',
    'Nyírlugos': '2.0', 'Nyírlövő': '2.0', 'Nyírkércs': '1.4', 'Nyírkáta': '0.0', 'Nyírkarász': '1.6',
    'Nyírjákó': '0.0', 'Nyíribrony': '1.8', 'Nyírgyulaj': '1.8', 'Nyírgelse': '1.3', 'Nyíregyháza': '2.0',
    'Nyírderzs': '0.8', 'Nyírcsászári': '0.0', 'Nyírcsaholy': '1.0', 'Nyírbogdány': '2.0',
    'Nyírbogát': '1.5', 'Nyírbéltek': '1.3', 'Nyírbátor': '2.0', 'Nemesborzova': '0.0', 'Napkor': '1.5',
    'Nagyvarsány': '1.7', 'Nagyszekeres': '1.0', 'Nagykálló': '2.0', 'Nagyhódos': '0.0', 'Nagyecsed': '2.0',
    'Nagydobos': '1.4', 'Nagycserkesz': '2.0', 'Nagyar': '2.0', 'Nábrád': '1.5', 'Milota': '1.5',
    'Mezőladány': '1.4', 'Mérk': '1.1', 'Méhtelek': '0.0', 'Mátyus': '1.4', 'Mátészalka': '2.0',
    'Márokpapi': '1.5', 'Máriapócs': '2.0', 'Mándok': '2.0', 'Mánd': '1.0', 'Magy': '0.0',
    'Magosliget': '0.0', 'Lövőpetri': '1.5', 'Lónya': '1.5', 'Levelek': '1.2', 'Laskod': '1.2',
    'Kömörő': '0.5', 'Kölcse': '1.7', 'Kótaj': '2.0', 'Komoró': '2.0', 'Kocsord': '1.0',
    'Kisszekeres': '1.0', 'Kisvarsány': '2.0', 'Kisvárda': '2.0', 'Kispalád': '0.0', 'Kisnamény': '0.0',
    'Kisléta': '1.4', 'Kishódos': '0.0', 'Kisar': '2.0', 'Kérsemjén': '1.0', 'Kemecse': '1.7',
    'Kékcse': '1.6', 'Kék': '1.4', 'Kántorjánosi': '0.0', 'Kálmánháza': '2.0', 'Kállósemjén': '2.0',
    'Jéke': '1.0', 'Jármi': '2.0', 'Jánkmajtis': '1.7', 'Jánd': '2.0', 'Ilk': '1.4', 'Ibrány': '1.7',
    'Hodász': '1.0', 'Hetefejércse': '1.5', 'Hermánszeg': '0.0', 'Gyüre': '0.0', 'Gyügye': '0.0',
    'Gyulaháza': '0.0', 'Győrtelek': '2.0', 'Győröcske': '2.0', 'Gulács': '2.0', 'Geszteréd': '2.0',
    'Gemzse': '0.0', 'Gelénes': '1.0', 'Gégény': '2.0', 'Géberjén': '1.7', 'Gávavencsellő': '1.8',
    'Garbolc': '0.0', 'Gacsály': '0.0', 'Fülpösdaróc': '2.0', 'Fülesd': '0.0', 'Fényeslitke': '2.0',
    'Fehérgyarmat': '2.0', 'Fábiánháza': '1.5', 'Érpatak': '2.0', 'Eperjeske': '1.4', 'Encsencs': '1.2',
    'Döge': '1.8', 'Dombrád': '2.0', 'Demecser': '2.0', 'Darnó': '2.0', 'Csengerújfalu': '1.0',
    'Csengersima': '2.0', 'Csenger': '2.0', 'Csegöld': '1.0', 'Császló': '0.0', 'Csaroda': '1.3',
    'Csaholc': '0.0', 'Cégénydányád': '1.0', 'Buj': '2.0', 'Bököny': '1.8', 'Botpalád': '0.0', 'Biri': '1.5',
    'Beszterec': '1.0', 'Besenyőd': '1.5', 'Berkesz': '1.4', 'Beregsurány': '2.0', 'Beregdaróc': '2.0',
    'Benk': '0.0', 'Bátorliget': '0.0', 'Barabás': '1.4', 'Balsa': '1.8', 'Balkány': '1.7',
    'Baktalórántháza': '1.5', 'Aranyosapáti': '1.7', 'Apagy': '1.5', 'Anarcs': '1.9', 'Ajak': '1.7',
    'Zselicszentpál': '1.5', 'Zselickislak': '2.0', 'Zselickisfalud': '1.2', 'Zimány': '2.0', 'Zics': '1.7',
    'Zamárdi': '2.0', 'Zala': '1.5', 'Zákányfalu': '1.5', 'Zákány': '2.0', 'Vörs': '2.0', 'Vízvár': '2.0',
    'Visz': '2.0', 'Visnye': '2.0', 'Vése': '1.5', 'Várda': '2.0', 'Varászló': '2.0', 'Újvárfalva': '1.0',
    'Törökkoppány': '1.5', 'Tótújfalu': '1.0', 'Torvaj': '2.0', 'Tengőd': '1.0', 'Teleki': '1.7',
    'Taszár': '2.0', 'Táska': '2.0', 'Tarany': '1.8', 'Tapsony': '1.8', 'Tab': '2.0', 'Szulok': '0.8',
    'Szőlősgyörök': '1.5', 'Szőkedencs': '2.0', 'Szorosad': '1.5', 'Szólád': '1.4',
    'Szilvásszentmárton': '0.7', 'Szenyér': '2.0', 'Szentgáloskér': '2.0', 'Szentborbás': '1.0',
    'Szentbalázs': '2.0', 'Szenta': '1.4', 'Szenna': '1.5', 'Szegerdő': '2.0', 'Szántód': '2.0',
    'Szabás': '2.0', 'Szabadi': '2.0', 'Somogyzsitfa': '2.0', 'Somogyvár': '2.0', 'Somogyvámos': '2.0',
    'Somogyudvarhely': '2.0', 'Somogytúr': '2.0', 'Somogyszob': '2.0', 'Somogyszil': '2.0',
    'Somogyszentpál': '0.0', 'Somogysimonyi': '0.0', 'Somogysárd': '2.0', 'Somogysámson': '2.0',
    'Somogymeggyes': '2.0', 'Somogyjád': '2.0', 'Somogygeszti': '2.0', 'Somogyfajsz': '1.8',
    'Somogyegres': '2.0', 'Somogydöröcske': '1.5', 'Somogycsicsó': '0.0', 'Somogybükkösd': '0.0',
    'Somogybabod': '2.0', 'Somogyaszaló': '2.0', 'Somogyaracs': '2.0', 'Somogyacsa': '1.5', 'Somodor': '2.0',
    'Som': '2.0', 'Siójut': '1.5', 'Siófok': '2.0', 'Simonfa': '1.5', 'Sérsekszőlős': '2.0', 'Segesd': '2.0',
    'Sávoly': '2.0', 'Sántos': '2.0', 'Ságvár': '2.0', 'Rinyaújnép': '1.7', 'Rinyaújlak': '0.0',
    'Rinyaszentkirály': '2.0', 'Rinyakovácsi': '1.0', 'Rinyabesenyő': '2.0', 'Ráksi': '2.0',
    'Pusztaszemes': '1.5', 'Pusztakovácsi': '2.0', 'Potony': '1.6', 'Porrogszentpál': '0.0',
    'Porrogszentkirály': '0.0', 'Porrog': '0.0', 'Polány': '2.0', 'Pogányszentpéter': '2.0',
    'Péterhida': '1.7', 'Patosfa': '0.0', 'Patca': '0.0', 'Patalom': '1.4', 'Pamuk': '0.0',
    'Pálmajor': '0.8', 'Ötvöskónyi': '2.0', 'Őrtilos': '2.0', 'Öreglak': '2.0', 'Osztopán': '2.0',
    'Ordacsehi': '2.0', 'Orci': '2.0', 'Nyim': '2.0', 'Nikla': '2.0', 'Nemesvid': '2.0',
    'Nemeskisfalud': '2.0', 'Nemesdéd': '1.0', 'Nagyszakácsi': '1.5', 'Nagykorpád': '1.2',
    'Nagycsepely': '2.0', 'Nagyberki': '2.0', 'Nagyberény': '1.5', 'Nagybajom': '1.5', 'Nagyatád': '2.0',
    'Nágocs': '1.4', 'Mosdós': '2.0', 'Miklósi': '1.0', 'Mike': '0.0', 'Mezőcsokonya': '1.7',
    'Mesztegnyő': '2.0', 'Mernye': '1.7', 'Marcali': '2.0', 'Magyaregres': '2.0', 'Magyaratád': '1.6',
    'Lulla': '2.0', 'Libickozma': '2.0', 'Lengyeltóti': '2.0', 'Látrány': '2.0', 'Lakócsa': '1.0',
    'Lad': '0.0', 'Lábod': '1.6', 'Kutas': '2.0', 'Kötcse': '2.0', 'Kőröshegy': '2.0', 'Kőkút': '1.0',
    'Komlósd': '0.0', 'Kiskorpád': '1.5', 'Kisgyalán': '2.0', 'Kisberény': '2.0', 'Kisbárapáti': '1.5',
    'Kisbajom': '0.0', 'Kisasszond': '1.5', 'Kéthely': '1.8', 'Kereki': '2.0', 'Kercseliget': '2.0',
    'Kelevíz': '0.5', 'Kazsok': '2.0', 'Kaszó': '1.5', 'Kastélyosdombó': '0.5', 'Karád': '2.0',
    'Kára': '2.0', 'Kaposszerdahely': '1.7', 'Kaposvár': '2.0', 'Kaposújlak': '1.7', 'Kaposmérő': '1.5',
    'Kaposkeresztúr': '1.7', 'Kaposhomok': '2.0', 'Kaposgyarmat': '2.0', 'Kaposfő': '1.8', 'Kapoly': '2.0',
    'Kánya': '2.0', 'Kálmáncsa': '1.7', 'Kadarkút': '2.0', 'Juta': '2.0', 'Jákó': '2.0', 'Istvándi': '2.0',
    'Inke': '2.0', 'Iharosberény': '1.8', 'Iharos': '2.0', 'Igal': '2.0', 'Hosszúvíz': '0.0',
    'Homokszentgyörgy': '2.0', 'Hetes': '2.0', 'Heresznye': '2.0', 'Hencse': '2.0', 'Hedrehely': '1.5',
    'Háromfa': '2.0', 'Hajmás': '2.0', 'Hács': '2.0', 'Gyugy': '2.0', 'Gyékényes': '1.8', 'Görgeteg': '1.0',
    'Gölle': '1.8', 'Gige': '2.0', 'Gamás': '2.0', 'Gálosfa': '2.0', 'Gadány': '0.5', 'Gadács': '2.0',
    'Főnyed': '2.0', 'Fonyód': '1.8', 'Fonó': '1.7', 'Fiad': '2.0', 'Felsőmocsolád': '2.0', 'Edde': '2.0',
    'Ecseny': '2.0', 'Drávatamási': '0.5', 'Drávagárdony': '1.5', 'Darány': '1.5', 'Csurgónagymarton': '2.0',
    'Csurgó': '2.0', 'Csömend': '2.0', 'Csököly': '1.0', 'Csombárd': '1.5', 'Csoma': '2.0',
    'Csokonyavisonta': '0.0', 'Cserénfa': '2.0', 'Csákány': '2.0', 'Büssü': '2.0', 'Buzsák': '2.0',
    'Bőszénfa': '1.8', 'Böhönye': '2.0', 'Bonnya': '1.0', 'Bolhó': '2.0', 'Bolhás': '1.5', 'Bodrog': '2.0',
    'Berzence': '2.0', 'Beleg': '2.0', 'Bélavár': '2.0', 'Bedegkér': '2.0', 'Baté': '1.8',
    'Bárdudvarnok': '2.0', 'Barcs': '2.0', 'Bálványos': '1.4', 'Balatonvilágos': '1.6',
    'Balatonújlak': '1.8', 'Balatonszentgyörgy': '2.0', 'Balatonszemes': '2.0', 'Balatonszárszó': '2.0',
    'Balatonszabadi': '1.0', 'Balatonőszöd': '2.0', 'Balatonmáriafürdő': '2.0', 'Balatonlelle': '1.8',
    'Balatonkeresztúr': '1.8', 'Balatonföldvár': '2.0', 'Balatonfenyves': '2.0', 'Balatonendréd': '2.0',
    'Balatonboglár': '2.0', 'Balatonberény': '2.0', 'Bakháza': '0.0', 'Bábonymegyer': '2.0',
    'Babócsa': '2.0', 'Andocs': '2.0', 'Alsóbogát': '2.0', 'Ádánd': '1.5', 'Zsámbok': '1.5',
    'Zsámbék': '2.0', 'Zebegény': '2.0', 'Visegrád': '1.8', 'Verseg': '1.9', 'Verőce': '1.7',
    'Veresegyház': '2.0', 'Vecsés': '1.9', 'Vasad': '2.0', 'Vámosmikola': '2.0', 'Valkó': '2.0',
    'Vácszentlászló': '2.0', 'Vácrátót': '1.2', 'Váckisújfalu': '2.0', 'Váchartyán': '2.0',
    'Vácegres': '2.0', 'Vácduka': '2.0', 'Vác': '2.0', 'Üröm': '2.0', 'Üllő': '1.9', 'Úri': '1.7',
    'Újszilvás': '1.7', 'Újlengyel': '0.0', 'Újhartyán': '1.6', 'Tura': '2.0', 'Törtel': '2.0',
    'Törökbálint': '2.0', 'Tököl': '2.0', 'Tök': '2.0', 'Tóalmás': '1.4', 'Tinnye': '1.5', 'Tésa': '0.0',
    'Telki': '1.8', 'Tatárszentgyörgy': '2.0', 'Tárnok': '2.0', 'Tápiószőlős': '1.1',
    'Tápiószentmárton': '2.0', 'Tápiószele': '2.0', 'Tápiószecső': '1.5', 'Tápióság': '1.7',
    'Tápiógyörgye': '2.0', 'Tápióbicske': '1.7', 'Taksony': '2.0', 'Tahitótfalu': '1.5', 'Táborfalva': '2.0',
    'Sződliget': '1.6', 'Sződ': '1.4', 'Szokolya': '2.0', 'Szob': '2.0', 'Szigetújfalu': '1.8',
    'Szigetszentmiklós': '2.0', 'Szigetszentmárton': '1.8', 'Szigetmonostor': '1.5', 'Szigethalom': '1.8',
    'Szigetcsép': '2.0', 'Szigetbecse': '1.6', 'Szentmártonkáta': '2.0', 'Szentlőrinckáta': '1.4',
    'Szentendre': '2.0', 'Százhalombatta': '2.0', 'Szada': '2.0', 'Sülysáp': '1.7', 'Sóskút': '1.5',
    'Solymár': '1.85', 'Remeteszőlős': '1.4', 'Rád': '1.8', 'Püspökszilágy': '2.0', 'Püspökhatvan': '1.5',
    'Pusztazámor': '1.5', 'Pusztavacs': '2.0', 'Pomáz': '2.0', 'Pócsmegyer': '1.5',
    'Pilisszentlászló': '1.6', 'Pilisszentkereszt': '2.0', 'Pilisszentiván': '1.8', 'Pilisszántó': '1.5',
    'Pilisvörösvár': '1.85', 'Pilisjászfalu': '1.9', 'Piliscsaba': '1.85', 'Pilisborosjenő': '1.5',
    'Pilis': '2.0', 'Péteri': '1.9', 'Perőcsény': '1.5', 'Perbál': '2.0', 'Penc': '1.3', 'Pécel': '2.0',
    'Páty': '2.0', 'Pánd': '1.5', 'Örkény': '2.0', 'Őrbottyán': '1.9', 'Ócsa': '2.0', 'Nyársapát': '1.7',
    'Nyáregyháza': '2.0', 'Nagytarcsa': '1.5', 'Nagymaros': '2.0', 'Nagykőrös': '2.0', 'Nagykovácsi': '2.0',
    'Nagykáta': '2.0', 'Nagybörzsöny': '1.8', 'Monorierdő': '2.0', 'Monor': '2.0', 'Mogyoród': '1.8',
    'Mikebuda': '2.0', 'Mende': '2.0', 'Márianosztra': '2.0', 'Makád': '1.0', 'Majosháza': '2.0',
    'Maglód': '2.0', 'Lórév': '1.0', 'Letkés': '2.0', 'Leányfalu': '2.0', 'Kőröstetétlen': '2.0',
    'Kóspallag': '1.5', 'Kosd': '1.0', 'Kóka': '1.85', 'Kocsér': '1.5', 'Kistarcsa': '2.0',
    'Kisoroszi': '1.5', 'Kisnémedi': '2.0', 'Kismaros': '1.8', 'Kiskunlacháza': '2.0', 'Kerepes': '2.0',
    'Kemence': '1.6', 'Káva': '1.0', 'Kartal': '2.0', 'Kakucs': '2.0', 'Jászkarajenő': '1.8',
    'Isaszeg': '2.0', 'Ipolytölgyes': '1.5', 'Ipolydamásd': '1.5', 'Inárcs': '2.0', 'Iklad': '2.0',
    'Hévízgyörk': '2.0', 'Hernád': '2.0', 'Herceghalom': '2.0', 'Halásztelek': '1.8', 'Gyömrő': '2.0',
    'Gyál': '1.8', 'Gödöllő': '2.0', 'Göd': '2.0', 'Gomba': '2.0', 'Galgamácsa': '2.0', 'Galgahévíz': '2.0',
    'Galgagyörk': '2.0', 'Fót': '2.0', 'Felsőpakony': '2.0', 'Farmos': '1.9', 'Erdőkertes': '2.0',
    'Érd': '2.0', 'Ecser': '2.0', 'Dunavarsány': '2.0', 'Dunakeszi': '2.0', 'Dunaharaszti': '2.0',
    'Dunabogdány': '2.0', 'Dömsöd': '2.0', 'Domony': '2.0', 'Diósd': '2.0', 'Délegyháza': '2.0',
    'Dány': '1.8', 'Dánszentmiklós': '1.7', 'Dabas': '2.0', 'Csővár': '0.0', 'Csörög': '1.7',
    'Csömör': '2.0', 'Csomád': '0.0', 'Csobánka': '2.0', 'Csévharaszt': '2.0', 'Csemő': '1.5',
    'Ceglédbercel': '2.0', 'Cegléd': '2.0', 'Bugyi': '2.0', 'Budaörs': '1.9', 'Budakeszi': '2.0',
    'Budakalász': '2.0', 'Budajenő': '1.8', 'Biatorbágy': '2.0', 'Bernecebaráti': '1.4', 'Bénye': '2.0',
    'Bag': '2.0', 'Aszód': '2.0', 'Áporka': '1.9', 'Apaj': '0.9', 'Albertirsa': '2.0', 'Acsa': '1.0',
    'Abony': '2.0', 'Zabar': '0.0', 'Vizslás': '0.0', 'Varsány': '1.8', 'Vanyarc': '1.5', 'Tolmács': '2.0',
    'Tereske': '2.0', 'Terény': '1.5', 'Tar': '1.5', 'Szügy': '2.0', 'Szurdokpüspöki': '1.5', 'Szuha': '1.0',
    'Szirák': '2.0', 'Szilaspogony': '2.0', 'Szente': '2.0', 'Szendehely': '1.6', 'Szécsényfelfalu': '1.4',
    'Szécsény': '2.0', 'Szécsénke': '2.0', 'Szátok': '2.0', 'Szarvasgede': '0.5', 'Szanda': '2.0',
    'Szalmatercs': '1.5', 'Sóshartyán': '1.0', 'Somoskőújfalu': '1.8', 'Sámsonháza': '0.0',
    'Salgótarján': '2.0', 'Ságújfalu': '2.0', 'Romhány': '2.0', 'Rimóc': '1.5', 'Rétság': '2.0',
    'Rákóczibánya': '2.0', 'Pusztaberki': '2.0', 'Piliny': '1.5', 'Patvarc': '2.0', 'Patak': '1.8',
    'Pásztó': '2.0', 'Palotás': '1.8', 'Ősagárd': '1.5', 'Őrhalom': '2.0', 'Nőtincs': '1.5',
    'Nógrádszakál': '1.5', 'Nógrádsipek': '1.5', 'Nógrádsáp': '1.8', 'Nógrádmegyer': '1.5',
    'Nógrádmarcal': '2.0', 'Nógrádkövesd': '2.0', 'Nógrád': '1.7', 'Nézsa': '1.5', 'Nemti': '2.0',
    'Nagyoroszi': '2.0', 'Nagylóc': '2.0', 'Nagykeresztúr': '1.0', 'Nagybárkány': '1.0', 'Mohora': '2.0',
    'Mihálygerge': '2.0', 'Mátraverebély': '1.5', 'Mátraterenye': '2.0', 'Mátraszőlős': '1.5',
    'Mátraszele': '2.0', 'Mátranovák': '2.0', 'Mátramindszent': '1.5', 'Márkháza': '0.0',
    'Magyarnándor': '2.0', 'Magyargéc': '1.8', 'Ludányhalászi': '2.0', 'Lucfalva': '1.5', 'Litke': '1.7',
    'Legénd': '2.0', 'Kutasó': '0.0', 'Kozárd': '1.0', 'Kishartyán': '1.0', 'Kisecset': '2.0',
    'Kisbárkány': '0.0', 'Kisbágyon': '1.0', 'Kétbodony': '2.0', 'Keszeg': '2.0', 'Kazár': '1.7',
    'Karancsság': '2.0', 'Karancslapujtő': '1.0', 'Karancskeszi': '1.4', 'Karancsberény': '1.5',
    'Karancsalja': '1.5', 'Kálló': '2.0', 'Jobbágyi': '2.0', 'Ipolyvece': '1.8', 'Ipolytarnóc': '2.0',
    'Ipolyszög': '2.0', 'Iliny': '1.5', 'Hugyag': '0.5', 'Horpács': '2.0', 'Hont': '2.0', 'Hollókő': '1.5',
    'Herencsény': '1.4', 'Héhalom': '2.0', 'Garáb': '0.0', 'Galgaguta': '2.0', 'Felsőtold': '0.0',
    'Felsőpetény': '2.0', 'Etes': '2.0', 'Érsekvadkert': '2.0', 'Erdőtarcsa': '2.0', 'Erdőkürt': '1.5',
    'Endrefalva': '2.0', 'Egyházasgerge': '2.0', 'Egyházasdengeleg': '0.0', 'Ecseg': '2.0',
    'Drégelypalánk': '1.8', 'Dorogháza': '1.5', 'Diósjenő': '1.8', 'Dejtár': '1.8', 'Debercsény': '1.0',
    'Csitár': '1.0', 'Csesztve': '2.0', 'Cserhátszentiván': '0.0', 'Cserhátsurány': '1.5',
    'Cserháthaláp': '2.0', 'Csécse': '1.0', 'Cered': '2.0', 'Buják': '1.8', 'Borsosberény': '2.0',
    'Bokor': '0.0', 'Berkenye': '1.5', 'Bercel': '1.4', 'Bér': '1.5', 'Becske': '1.6',
    'Bátonyterenye': '2.0', 'Bárna': '2.0', 'Bánk': '1.7', 'Balassagyarmat': '2.0', 'Alsótold': '1.0',
    'Alsópetény': '1.4', 'Vértesszőlős': '2.0', 'Vértestolna': '1.5', 'Vértessomló': '1.9',
    'Vérteskethely': '2.0', 'Várgesztes': '1.8', 'Úny': '2.0', 'Tokodaltáró': '2.0', 'Tokod': '2.0',
    'Tatabánya': '2.0', 'Tata': '2.0', 'Tát': '2.0', 'Tárkány': '2.0', 'Tarján': '2.0', 'Tardos': '2.0',
    'Szomor': '2.0', 'Szomód': '1.8', 'Szárliget': '2.0', 'Szákszend': '2.0', 'Süttő': '2.0', 'Súr': '2.0',
    'Sárisáp': '2.0', 'Réde': '1.5', 'Pilismarót': '2.0', 'Piliscsév': '2.0', 'Oroszlány': '2.0',
    'Nyergesújfalu': '1.9', 'Neszmély': '2.0', 'Naszály': '2.0', 'Nagysáp': '2.0', 'Nagyigmánd': '2.0',
    'Mogyorósbánya': '1.5', 'Mocsa': '2.0', 'Máriahalom': '2.0', 'Leányvár': '2.0', 'Lábatlan': '2.0',
    'Környe': '2.0', 'Kömlőd': '1.5', 'Komárom': '2.0', 'Kocs': '2.0', 'Kisigmánd': '2.0', 'Kisbér': '2.0',
    'Kesztölc': '2.0', 'Kerékteleki': '2.0', 'Kecskéd': '1.8', 'Héreg': '2.0', 'Gyermely': '2.0',
    'Ete': '2.0', 'Esztergom': '2.0', 'Epöl': '2.0', 'Dunaszentmiklós': '1.8', 'Dunaalmás': '1.5',
    'Dömös': '1.5', 'Dorog': '2.0', 'Dág': '2.0', 'Dad': '2.0', 'Csolnok': '2.0', 'Csép': '2.0',
    'Csém': '1.8', 'Csatka': '1.3', 'Császár': '1.6', 'Bokod': '2.0', 'Bársonyos': '2.0', 'Bana': '2.0',
    'Bakonyszombathely': '2.0', 'Bakonysárkány': '2.0', 'Bakonybánk': '1.9', 'Bajót': '1.5', 'Bajna': '1.9',
    'Baj': '2.0', 'Bábolna': '2.0', 'Ászár': '2.0', 'Annavölgy': '0.0', 'Almásfüzitő': '2.0', 'Aka': '1.0',
    'Ácsteszér': '1.5', 'Ács': '2.0', 'Zaránk': '1.6', 'Zagyvaszántó': '0.8', 'Visznek': '1.8',
    'Visonta': '2.0', 'Verpelét': '1.8', 'Vécs': '2.0', 'Váraszó': '2.0', 'Vámosgyörk': '2.0',
    'Újlőrincfalva': '0.0', 'Tófalu': '1.0', 'Terpes': '1.3', 'Tenk': '1.0', 'Tarnazsadány': '2.0',
    'Tarnaszentmiklós': '2.0', 'Tarnaszentmária': '0.8', 'Tarnaörs': '1.4', 'Tarnaméra': '1.4',
    'Tarnalelesz': '2.0', 'Tarnabod': '0.0', 'Szűcsi': '1.9', 'Szúcs': '1.0', 'Szilvásvárad': '2.0',
    'Szihalom': '1.8', 'Szentdomonkos': '2.0', 'Szarvaskő': '1.8', 'Szajla': '1.0', 'Sirok': '2.0',
    'Sarud': '1.1', 'Rózsaszentmárton': '2.0', 'Recsk': '2.0', 'Poroszló': '1.5', 'Petőfibánya': '1.5',
    'Pétervására': '2.0', 'Pély': '1.5', 'Parádsasvár': '2.0', 'Parád': '1.5', 'Pálosvörösmart': '2.0',
    'Ostoros': '1.65', 'Novaj': '1.6', 'Noszvaj': '1.8', 'Nagyvisnyó': '1.6', 'Nagyút': '1.8',
    'Nagytálya': '1.4', 'Nagyréde': '2.0', 'Nagykökényes': '0.0', 'Nagyfüged': '1.4', 'Mónosbél': '2.0',
    'Mikófalva': '2.0', 'Mezőtárkány': '2.0', 'Mezőszemere': '2.0', 'Mátraszentimre': '1.8',
    'Mátraderecske': '2.0', 'Mátraballa': '2.0', 'Markaz': '2.0', 'Maklár': '1.4', 'Ludas': '2.0',
    'Lőrinci': '2.0', 'Kömlő': '0.5', 'Kompolt': '1.5', 'Kisnána': '2.0', 'Kisköre': '2.0',
    'Kisfüzes': '1.4', 'Kerekharaszt': '1.9', 'Kerecsend': '1.7', 'Karácsond': '2.0', 'Kápolna': '1.5',
    'Kál': '1.9', 'Ivád': '2.0', 'Istenmezeje': '2.0', 'Hort': '2.0', 'Hevesvezekény': '1.0',
    'Hevesaranyos': '1.5', 'Heves': '2.0', 'Heréd': '1.5', 'Hatvan': '1.9', 'Halmajugra': '2.0',
    'Gyöngyöstarján': '2.0', 'Gyöngyössolymos': '1.9', 'Gyöngyöspata': '1.5', 'Gyöngyösoroszi': '2.0',
    'Gyöngyöshalász': '2.0', 'Gyöngyös': '2.0', 'Füzesabony': '2.0', 'Felsőtárkány': '2.0',
    'Feldebrő': '2.0', 'Fedémes': '2.0', 'Erk': '1.0', 'Erdőtelek': '1.5', 'Erdőkövesd': '2.0',
    'Egerszólát': '1.8', 'Egerszalók': '1.5', 'Egerfarmos': '1.4', 'Egercsehi': '2.0', 'Egerbocs': '1.2',
    'Egerbakta': '1.4', 'Eger': '2.0', 'Ecséd': '2.0', 'Dormánd': '2.0', 'Domoszló': '1.7', 'Detk': '2.0',
    'Demjén': '1.5', 'Csány': '1.8', 'Bükkszentmárton': '2.0', 'Bükkszenterzsébet': '2.0', 'Bükkszék': '1.8',
    'Boldog': '2.0', 'Bodony': '1.5', 'Boconád': '1.4', 'Besenyőtelek': '1.5', 'Bélapátfalva': '2.0',
    'Bekölce': '2.0', 'Bátor': '2.0', 'Balaton': '2.0', 'Atkár': '2.0', 'Átány': '1.5', 'Apc': '1.9',
    'Andornaktálya': '1.8', 'Aldebrő': '2.0', 'Adács': '1.8', 'Abasár': '2.0', 'Zsáka': '2.0',
    'Vekerd': '0.0', 'Váncsod': '2.0', 'Vámospércs': '2.0', 'Újtikos': '1.5', 'Újszentmargita': '2.0',
    'Újléta': '2.0', 'Újiráz': '2.0', 'Told': '2.0', 'Tiszagyulaháza': '1.5', 'Tiszacsege': '2.0',
    'Tetétlen': '2.0', 'Tépe': '1.8', 'Téglás': '2.0', 'Szerep': '1.5', 'Szentpéterszeg': '1.6',
    'Sárrétudvari': '1.6', 'Sáránd': '2.0', 'Sáp': '1.7', 'Püspökladány': '1.5', 'Polgár': '2.0',
    'Pocsaj': '1.5', 'Nyírmártonfalva': '2.0', 'Nyíradony': '2.0', 'Nyíracsád': '1.6', 'Nyírábrány': '2.0',
    'Nagyrábé': '2.0', 'Nagykereki': '2.0', 'Nagyhegyes': '2.0', 'Nádudvar': '2.0', 'Monostorpályi': '2.0',
    'Mikepércs': '2.0', 'Mezősas': '2.0', 'Mezőpeterd': '2.0', 'Magyarhomorog': '2.0', 'Létavértes': '1.6',
    'Körösszegapáti': '1.4', 'Körösszakál': '2.0', 'Konyár': '1.8', 'Komádi': '2.0', 'Kokad': '1.0',
    'Kismarja': '1.5', 'Kaba': '2.0', 'Hosszúpályi': '2.0', 'Hortobágy': '2.0', 'Hencida': '1.0',
    'Hajdúszovát': '2.0', 'Hajdúszoboszló': '2.0', 'Hajdúsámson': '2.0', 'Hajdúnánás': '2.0',
    'Hajdúhadház': '2.0', 'Hajdúdorog': '1.8', 'Hajdúböszörmény': '2.0', 'Hajdúbagos': '2.0',
    'Görbeháza': '2.0', 'Gáborján': '1.6', 'Fülöp': '2.0', 'Furta': '2.0', 'Földes': '2.0', 'Folyás': '2.0',
    'Esztár': '1.5', 'Egyek': '2.0', 'Ebes': '1.8', 'Derecske': '2.0', 'Debrecen': '2.0', 'Darvas': '2.0',
    'Csökmő': '1.6', 'Bojt': '1.5', 'Bocskaikert': '2.0', 'Bihartorda': '1.6', 'Biharnagybajom': '1.7',
    'Bihardancsháza': '0.5', 'Berettyóújfalu': '2.0', 'Berekböszörmény': '1.5', 'Bedő': '2.0',
    'Báránd': '1.3', 'Balmazújváros': '2.0', 'Bakonszeg': '1.8', 'Bagamér': '1.4', 'Álmosd': '2.0',
    'Zsira': '1.0', 'Zsebeháza': '2.0', 'Völcsej': '1.7', 'Vitnyéd': '1.5', 'Veszprémvarsány': '1.7',
    'Veszkény': '1.2', 'Vének': '1.4', 'Vásárosfalu': '0.0', 'Várbalog': '2.0', 'Vámosszabadi': '1.4',
    'Vág': '2.0', 'Vadosfa': '1.2', 'Und': '0.0', 'Újrónafő': '1.85', 'Újkér': '1.8', 'Töltéstava': '1.4',
    'Tét': '1.7', 'Tényő': '0.0', 'Tarjánpuszta': '0.0', 'Tápszentmiklós': '0.0', 'Táp': '2.0',
    'Szilsárkány': '2.0', 'Szil': '1.9', 'Szerecseny': '1.6', 'Szárföld': '1.2', 'Szany': '2.0',
    'Szakony': '0.0', 'Sopronnémeti': '1.4', 'Sopronkövesd': '1.7', 'Sopronhorpács': '1.7', 'Sopron': '2.0',
    'Sokorópátka': '1.7', 'Sobor': '1.5', 'Sikátor': '1.7', 'Sarród': '2.0', 'Röjtökmuzsaj': '1.5',
    'Románd': '2.0', 'Rétalap': '1.5', 'Répcevis': '1.0', 'Répceszemere': '1.0', 'Ravazd': '1.7',
    'Rajka': '2.0', 'Rábcakapi': '0.0', 'Rábatamási': '1.6', 'Rábaszentmiklós': '0.0',
    'Rábaszentmihály': '1.3', 'Rábaszentandrás': '2.0', 'Rábasebes': '1.4', 'Rábapordány': '1.5',
    'Rábapatona': '1.6', 'Rábakecöl': '2.0', 'Rábacsécsény': '0.0', 'Rábacsanak': '2.0', 'Püski': '2.0',
    'Pusztacsalád': '1.0', 'Potyond': '2.0', 'Pinnye': '1.8', 'Petőháza': '2.0', 'Pereszteg': '1.8',
    'Pér': '2.0', 'Pázmándfalu': '2.0', 'Pásztori': '2.0', 'Pannonhalma': '2.0', 'Páli': '0.7',
    'Öttevény': '2.0', 'Osli': '1.4', 'Nyúl': '1.7', 'Nyalka': '1.5', 'Nemeskér': '0.0',
    'Nagyszentjános': '2.0', 'Nagylózs': '2.0', 'Nagycenk': '1.9', 'Nagybajcs': '1.3', 'Mosonudvar': '1.65',
    'Mosonszolnok': '1.8', 'Mosonszentmiklós': '2.0', 'Mosonmagyaróvár': '2.0', 'Mórichida': '2.0',
    'Mihályi': '1.4', 'Mezőörs': '0.9', 'Mérges': '0.0', 'Mecsér': '1.5', 'Markotabödöge': '0.0',
    'Máriakálnok': '2.0', 'Magyarkeresztúr': '1.5', 'Maglóca': '0.0', 'Lövő': '1.7', 'Lipót': '1.6',
    'Levél': '2.0', 'Lébény': '2.0', 'Lázi': '2.0', 'Kunsziget': '1.6', 'Koroncó': '1.7', 'Kópháza': '1.6',
    'Kóny': '1.4', 'Kisfalud': '1.8', 'Kisbodak': '2.0', 'Kisbajcs': '1.4', 'Kisbabot': '0.0',
    'Kimle': '2.0', 'Károlyháza': '2.0', 'Kapuvár': '2.0', 'Kajárpéc': '1.7', 'Jobaháza': '2.0',
    'Jánossomorja': '2.0', 'Iván': '1.0', 'Ikrény': '1.5', 'Hövej': '1.5', 'Himod': '0.5', 'Hidegség': '1.0',
    'Hegykő': '1.8', 'Hegyeshalom': '1.9', 'Hédervár': '2.0', 'Harka': '1.5', 'Halászi': '2.0',
    'Győrzámoly': '1.7', 'Győrújfalu': '1.4', 'Győrújbarát': '1.9', 'Győrszemere': '1.5',
    'Győrsövényház': '1.4', 'Győrság': '1.7', 'Győrladamér': '1.6', 'Győrasszonyfa': '1.8', 'Győr': '1.6',
    'Gyömöre': '1.6', 'Gyóró': '0.8', 'Gyarmat': '1.4', 'Gyalóka': '0.0', 'Gönyű': '2.0',
    'Fertőszéplak': '2.0', 'Fertőszentmiklós': '2.0', 'Fertőrákos': '1.5', 'Fertőhomok': '1.8',
    'Fertőendréd': '1.8', 'Fertőd': '2.0', 'Fertőboz': '2.0', 'Fenyőfő': '1.0', 'Felpéc': '1.5',
    'Feketeerdő': '1.7', 'Fehértó': '0.0', 'Farád': '2.0', 'Enese': '1.4', 'Egyházasfalu': '1.8',
    'Egyed': '1.0', 'Edve': '0.0', 'Écs': '1.8', 'Ebergőc': '2.0', 'Dunasziget': '0.7',
    'Dunaszentpál': '1.8', 'Dunaszeg': '1.7', 'Dunaremete': '2.0', 'Dunakiliti': '1.8', 'Dénesfa': '0.0',
    'Darnózseli': '2.0', 'Csorna': '2.0', 'Csikvánd': '1.7', 'Csér': '2.0', 'Csapod': '1.0',
    'Csáfordjánosfa': '2.0', 'Cirák': '0.0', 'Cakóháza': '0.0', 'Börcs': '2.0', 'Bőny': '1.8',
    'Bogyoszló': '2.0', 'Bodonhely': '0.0', 'Bezi': '1.0', 'Bezenye': '2.0', 'Beled': '1.8',
    'Barbacs': '2.0', 'Bakonyszentlászló': '1.6', 'Bakonypéterd': '1.4', 'Bakonygyirót': '1.6',
    'Bágyogszovát': '1.4', 'Babót': '1.3', 'Ásványráró': '2.0', 'Árpás': '1.0', 'Agyagosszergény': '2.0',
    'Ágfalva': '2.0', 'Acsalag': '1.0', 'Abda': '2.0', 'Zichyújfalu': '1.9', 'Zámoly': '2.0',
    'Vértesboglár': '1.9', 'Vértesacsa': '2.0', 'Vereb': '2.0', 'Velence': '2.0', 'Vál': '2.0',
    'Vajta': '1.0', 'Úrhida': '1.2', 'Újbarok': '1.8', 'Tordas': '2.0', 'Tác': '1.5', 'Tabajd': '1.7',
    'Székesfehérvár': '2.0', 'Szár': '1.9', 'Szabadhídvég': '2.0', 'Szabadegyháza': '2.0',
    'Szabadbattyán': '1.6', 'Sukoró': '2.0', 'Söréd': '1.25', 'Soponya': '1.6', 'Seregélyes': '2.0',
    'Sárszentmihály': '0.0', 'Sárszentágota': '1.5', 'Sárosd': '2.0', 'Sárkeszi': '1.4',
    'Sárkeresztes': '2.0', 'Sáregres': '1.8', 'Sárbogárd': '2.0', 'Ráckeresztúr': '2.0', 'Rácalmás': '2.0',
    'Pusztavám': '2.0', 'Pusztaszabolcs': '2.0', 'Polgárdi': '2.0', 'Perkáta': '2.0', 'Pázmánd': '2.0',
    'Pátka': '1.7', 'Pákozd': '1.4', 'Óbarok': '1.5', 'Nagyvenyim': '1.8', 'Nagyveleg': '0.5',
    'Nagylók': '2.0', 'Nagykarácsony': '1.7', 'Nádasdladány': '1.8', 'Nadap': '0.0', 'Mór': '2.0',
    'Moha': '2.0', 'Mezőszilas': '2.0', 'Mezőszentgyörgy': '2.0', 'Mezőkomárom': '2.0', 'Mezőfalva': '1.8',
    'Mátyásdomb': '2.0', 'Martonvásár': '2.0', 'Mány': '2.0', 'Magyaralmás': '1.9', 'Lovasberény': '1.6',
    'Lepsény': '2.0', 'Lajoskomárom': '2.0', 'Kulcs': '2.0', 'Kőszárhegy': '2.0', 'Kisláng': '1.5',
    'Kisapostag': '1.8', 'Kincsesbánya': '1.8', 'Kápolnásnyék': '2.0', 'Káloz': '2.0', 'Kajászó': '2.0',
    'Jenő': '1.4', 'Iváncsa': '1.5', 'Isztimér': '1.8', 'Iszkaszentgyörgy': '2.0', 'Igar': '1.5',
    'Hantos': '2.0', 'Gyúró': '2.0', 'Gárdony': '2.0', 'Gánt': '2.0', 'Füle': '1.8', 'Felcsút': '1.4',
    'Fehérvárcsurgó': '2.0', 'Etyek': '1.6', 'Ercsi': '2.0', 'Enying': '2.0', 'Előszállás': '2.0',
    'Dunaújváros': '2.0', 'Dég': '2.0', 'Daruszentmiklós': '2.0', 'Csősz': '2.0', 'Csór': '1.4',
    'Csókakő': '2.0', 'Csákvár': '1.8', 'Csákberény': '1.7', 'Csabdi': '1.5', 'Cece': '1.5', 'Bodajk': '2.0',
    'Bicske': '2.0', 'Besnyő': '1.5', 'Beloiannisz': '2.0', 'Baracska': '1.8', 'Baracs': '2.0',
    'Balinka': '2.0', 'Bakonykúti': '1.5', 'Bakonycsernye': '2.0', 'Alsószentiván': '1.5',
    'Alcsútdoboz': '2.0', 'Alap': '1.5', 'Adony': '1.5', 'Aba': '1.8', 'Zsombó': '2.0', 'Zákányszék': '1.8',
    'Üllés': '2.0', 'Újszentiván': '1.5', 'Tömörkény': '2.0', 'Tiszasziget': '1.5', 'Szentes': '2.0',
    'Székkutas': '2.0', 'Szegvár': '2.0', 'Szeged': '2.0', 'Szatymaz': '1.7', 'Sándorfalva': '2.0',
    'Ruzsa': '2.0', 'Röszke': '1.8', 'Pusztaszer': '1.6', 'Pusztamérges': '2.0', 'Pitvaros': '1.4',
    'Öttömös': '2.0', 'Ópusztaszer': '1.5', 'Óföldeák': '2.0', 'Nagytőke': '1.8', 'Nagymágocs': '2.0',
    'Nagylak': '2.0', 'Nagyér': '2.0', 'Mórahalom': '2.0', 'Mindszent': '2.0', 'Mártély': '2.0',
    'Maroslele': '2.0', 'Makó': '2.0', 'Magyarcsanád': '2.0', 'Kübekháza': '2.0', 'Kövegy': '1.5',
    'Klárafalva': '2.0', 'Kiszombor': '1.8', 'Kistelek': '2.0', 'Királyhegyes': '2.0',
    'Hódmezővásárhely': '2.0', 'Földeák': '2.0', 'Forráskút': '2.0', 'Ferencszállás': '2.0', 'Felgyő': '2.0',
    'Fábiánsebestyén': '2.0', 'Eperjes': '2.0', 'Domaszék': '2.0', 'Dóc': '2.0', 'Deszk': '2.0',
    'Derekegyház': '2.0', 'Csongrád': '2.0', 'Csengele': '2.0', 'Csanytelek': '2.0', 'Csanádpalota': '2.0',
    'Csanádalberti': '2.0', 'Bordány': '2.0', 'Balástya': '2.0', 'Baks': '1.9', 'Ásotthalom': '2.0',
    'Árpádhalom': '2.0', 'Apátfalva': '2.0', 'Ambrózfalva': '2.0', 'Algyő': '2.0', 'Zsujta': '1.5',
    'Zubogy': '2.0', 'Ziliz': '2.0', 'Zemplénagárd': '2.0', 'Zalkod': '2.0', 'Zádorfalva': '2.0',
    'Vizsoly': '2.0', 'Viszló': '0.0', 'Viss': '2.0', 'Vilyvitány': '1.5', 'Vilmány': '2.0', 'Vatta': '2.0',
    'Varbóc': '0.0', 'Varbó': '1.8', 'Vámosújfalu': '1.5', 'Vajdácska': '2.0', 'Vágáshuta': '1.5',
    'Vadna': '2.0', 'Uppony': '2.0', 'Újcsanálos': '1.7', 'Trizs': '1.4', 'Tornyosnémeti': '2.0',
    'Tornaszentjakab': '2.0', 'Tornaszentandrás': '1.0', 'Tornanádaska': '1.0', 'Tornakápolna': '0.0',
    'Tornabarakony': '1.5', 'Tomor': '2.0', 'Tolcsva': '2.0', 'Tokaj': '2.0', 'Tiszavalk': '2.0',
    'Tiszaújváros': '1.5', 'Tiszatarján': '2.0', 'Tiszatardos': '0.9', 'Tiszapalkonya': '1.3',
    'Tiszalúc': '1.8', 'Tiszaladány': '2.0', 'Tiszakeszi': '2.0', 'Tiszakarád': '1.5', 'Tiszadorogma': '1.0',
    'Tiszacsermely': '1.8', 'Tiszabábolna': '2.0', 'Tibolddaróc': '2.0', 'Teresztenye': '0.0',
    'Telkibánya': '1.7', 'Tardona': '0.2', 'Tard': '2.0', 'Tarcal': '2.0', 'Tállya': '2.0',
    'Taktaszada': '1.9', 'Taktakenéz': '2.0', 'Taktaharkány': '1.6', 'Taktabáj': '2.0', 'Szuhogy': '2.0',
    'Szuhakálló': '2.0', 'Szuhafő': '2.0', 'Szögliget': '1.5', 'Szomolya': '2.0', 'Szinpetri': '0.0',
    'Szin': '0.0', 'Szikszó': '2.0', 'Szerencs': '1.9', 'Szentistvánbaksa': '2.0', 'Szentistván': '1.8',
    'Szendrőlád': '1.5', 'Szendrő': '2.0', 'Szemere': '2.0', 'Szegilong': '2.0', 'Szegi': '2.0',
    'Szászfa': '2.0', 'Szalonna': '1.7', 'Szalaszend': '1.2', 'Szakáld': '1.5', 'Szakácsi': '2.0',
    'Sóstófalva': '2.0', 'Sima': '0.7', 'Serényfalva': '2.0', 'Semjén': '1.0', 'Selyeb': '2.0',
    'Sátoraljaújhely': '2.0', 'Sáta': '2.0', 'Sárospatak': '2.0', 'Sárazsadány': '1.5', 'Sály': '1.5',
    'Sajóvelezd': '2.0', 'Sajóvámos': '2.0', 'Sajószöged': '2.0', 'Sajószentpéter': '2.0',
    'Sajósenye': '2.0', 'Sajópüspöki': '2.0', 'Sajópetri': '2.0', 'Sajópálfala': '2.0', 'Sajóörös': '2.0',
    'Sajónémeti': '2.0', 'Sajómercse': '2.0', 'Sajólászlófalva': '2.0', 'Sajólád': '2.0',
    'Sajókeresztúr': '2.0', 'Sajókaza': '2.0', 'Sajóivánka': '2.0', 'Sajóhídvég': '1.6', 'Sajógalgóc': '2.0',
    'Sajóecseg': '1.5', 'Sajóbábony': '2.0', 'Rudolftelep': '1.5', 'Rudabánya': '1.5', 'Ricse': '2.0',
    'Révleányvár': '0.0', 'Répáshuta': '2.0', 'Regéc': '1.5', 'Rátka': '2.0', 'Rásonysápberencs': '1.0',
    'Rakacaszend': '2.0', 'Rakaca': '2.0', 'Ragály': '2.0', 'Radostyán': '2.0', 'Putnok': '2.0',
    'Pusztaradvány': '2.0', 'Pusztafalu': '2.0', 'Prügy': '2.0', 'Perecse': '2.0', 'Pere': '2.0',
    'Parasznya': '2.0', 'Pányok': '1.5', 'Pamlény': '2.0', 'Pálháza': '2.0', 'Pácin': '1.4', 'Ózd': '2.0',
    'Oszlár': '1.4', 'Ormosbánya': '1.8', 'Ónod': '1.6', 'Onga': '2.0', 'Olaszliszka': '1.5',
    'Nyomár': '2.0', 'Nyíri': '1.0', 'Nyésta': '0.0', 'Nyékládháza': '2.0', 'Novajidrány': '2.0',
    'Nemesbikk': '2.0', 'Nekézseny': '2.0', 'Négyes': '2.0', 'Nagyrozvágy': '0.5', 'Nagykinizs': '1.5',
    'Nagyhuta': '1.8', 'Nagycsécs': '1.6', 'Nagybarca': '2.0', 'Muhi': '2.0', 'Múcsony': '2.0',
    'Monok': '1.6', 'Monaj': '0.0', 'Mogyoróska': '1.5', 'Miskolc': '2.0', 'Mikóháza': '1.5',
    'Mezőzombor': '2.0', 'Mezőnyárád': '2.0', 'Mezőnagymihály': '1.6', 'Mezőkövesd': '2.0',
    'Mezőkeresztes': '2.0', 'Mezőcsát': '1.8', 'Meszes': '1.2', 'Méra': '2.0', 'Megyaszó': '1.5',
    'Martonyi': '2.0', 'Mályinka': '2.0', 'Mályi': '2.0', 'Makkoshotyka': '2.0', 'Mád': '2.0',
    'Litka': '1.0', 'Lénárddaróc': '2.0', 'Léh': '1.0', 'Legyesbénye': '1.7', 'Lak': '1.7',
    'Ládbesenyő': '0.0', 'Lácacséke': '2.0', 'Kurityán': '2.0', 'Kupa': '0.0', 'Krasznokvajda': '2.0',
    'Köröm': '2.0', 'Kovácsvágás': '2.0', 'Korlát': '0.0', 'Kondó': '2.0', 'Komlóska': '0.0',
    'Komjáti': '1.0', 'Kistokaj': '1.8', 'Kissikátor': '1.4', 'Kisrozvágy': '1.0', 'Kiskinizs': '2.0',
    'Kishuta': '1.2', 'Kisgyőr': '2.0', 'Kiscsécs': '2.0', 'Királd': '2.0', 'Kesznyéten': '2.0',
    'Keresztéte': '2.0', 'Kenézlő': '2.0', 'Kelemér': '2.0', 'Kéked': '1.4', 'Kázsmárk': '1.0',
    'Kazincbarcika': '2.0', 'Karos': '1.5', 'Karcsa': '1.5', 'Kány': '2.0', 'Kánó': '0.0', 'Kács': '2.0',
    'Jósvafő': '2.0', 'Járdánháza': '0.0', 'Jákfalva': '2.0', 'Izsófalva': '2.0', 'Irota': '0.0',
    'Ináncs': '2.0', 'Imola': '2.0', 'Igrici': '2.0', 'Homrogd': '1.2', 'Hollóháza': '2.0',
    'Hidvégardó': '1.7', 'Hidasnémeti': '2.0', 'Hét': '1.6', 'Hernádvécse': '2.0', 'Hernádszurdok': '2.0',
    'Hernádszentandrás': '1.5', 'Hernádpetri': '2.0', 'Hernádnémeti': '1.8', 'Hernádkércs': '2.0',
    'Hernádkak': '1.8', 'Hernádcéce': '2.0', 'Hernádbűd': '0.0', 'Hercegkút': '0.0', 'Hejőszalonta': '2.0',
    'Hejőpapi': '2.0', 'Hejőkürt': '1.8', 'Hejőkeresztúr': '2.0', 'Hejőbába': '2.0', 'Hejce': '0.0',
    'Hegymeg': '2.0', 'Harsány': '2.0', 'Háromhuta': '0.0', 'Hangony': '1.5', 'Hangács': '2.0',
    'Halmaj': '2.0', 'Györgytarló': '2.0', 'Göncruszka': '0.0', 'Gönc': '2.0', 'Gömörszőlős': '2.0',
    'Golop': '2.0', 'Girincs': '2.0', 'Gibárt': '2.0', 'Gesztely': '2.0', 'Gelej': '2.0', 'Garadna': '2.0',
    'Galvács': '0.0', 'Gagyvendégi': '0.0', 'Gagybátor': '2.0', 'Gagyapáti': '1.0', 'Gadna': '0.0',
    'Füzérradvány': '1.8', 'Füzérkomlós': '1.0', 'Füzérkajata': '1.8', 'Füzér': '0.0', 'Fulókércs': '2.0',
    'Forró': '1.8', 'Fony': '0.0', 'Filkeháza': '1.8', 'Felsőzsolca': '2.0', 'Felsővadász': '1.0',
    'Felsőtelekes': '2.0', 'Felsőregmec': '1.0', 'Felsőnyárád': '1.8', 'Felsőkelecsény': '2.0',
    'Felsőgagy': '1.0', 'Felsődobsza': '2.0', 'Felsőberecki': '2.0', 'Farkaslyuk': '1.6', 'Fancsal': '1.0',
    'Fáj': '2.0', 'Erdőhorváti': '1.5', 'Erdőbénye': '1.5', 'Encs': '2.0', 'Emőd': '2.0', 'Egerlövő': '2.0',
    'Edelény': '2.0', 'Dubicsány': '0.0', 'Dövény': '2.0', 'Domaháza': '1.0', 'Detek': '1.5',
    'Dédestapolcsány': '2.0', 'Debréte': '2.0', 'Dámóc': '0.0', 'Damak': '1.0', 'Csokvaomány': '1.0',
    'Csobaj': '2.0', 'Csobád': '2.0', 'Csincse': '2.0', 'Csernely': '1.0', 'Cserépváralja': '2.0',
    'Cserépfalu': '2.0', 'Csenyéte': '1.0', 'Cigánd': '2.0', 'Büttös': '2.0', 'Bükkzsérc': '2.0',
    'Bükkszentkereszt': '2.0', 'Bükkmogyorósd': '0.0', 'Bükkaranyos': '1.5', 'Bükkábrány': '2.0',
    'Bőcs': '2.0', 'Bózsva': '1.0', 'Borsodszirák': '1.9', 'Borsodszentgyörgy': '1.8', 'Borsodnádasd': '2.0',
    'Borsodivánka': '2.0', 'Borsodgeszt': '2.0', 'Borsodbóta': '2.0', 'Boldva': '1.8',
    'Boldogkőváralja': '1.0', 'Boldogkőújfalu': '2.0', 'Bogács': '2.0', 'Bódvaszilas': '2.0',
    'Bódvarákó': '1.0', 'Bódvalenke': '2.0', 'Bodrogolaszi': '2.0', 'Bodrogkisfalud': '1.8',
    'Bodrogkeresztúr': '1.9', 'Bodroghalom': '1.5', 'Berzék': '1.6', 'Beret': '2.0', 'Berente': '2.0',
    'Bekecs': '2.0', 'Becskeháza': '2.0', 'Baskó': '2.0', 'Bánréve': '2.0', 'Bánhorváti': '1.9',
    'Balajt': '0.0', 'Baktakék': '1.0', 'Aszaló': '1.4', 'Ároktő': '2.0', 'Arnót': '1.7', 'Arló': '2.0',
    'Arka': '2.0', 'Alsózsolca': '2.0', 'Alsóvadász': '1.5', 'Alsótelekes': '1.0', 'Alsószuha': '1.0',
    'Alsóregmec': '1.4', 'Alsógagy': '0.5', 'Alsódobsza': '2.0', 'Alsóberecki': '1.5', 'Alacska': '2.0',
    'Aggtelek': '0.0', 'Abod': '', 'Abaújvár': '1.5', 'Abaújszolnok': '2.0', 'Abaújszántó': '1.75',
    'Abaújlak': '0.0', 'Abaújkér': '1.5', 'Abaújalpár': '0.0', 'Zsadány': '2.0', 'Vésztő': '2.0',
    'Végegyháza': '1.5', 'Újszalonta': '1.0', 'Újkígyós': '2.0', 'Tótkomlós': '1.8', 'Telekgerendás': '2.0',
    'Tarhos': '2.0', 'Szeghalom': '2.0', 'Szarvas': '2.0', 'Szabadkígyós': '2.0', 'Sarkadkeresztúr': '1.2',
    'Sarkad': '2.0', 'Pusztaottlaka': '0.9', 'Pusztaföldvár': '1.8', 'Örménykút': '1.8', 'Orosháza': '2.0',
    'Okány': '1.7', 'Nagyszénás': '2.0', 'Nagykamarás': '1.2', 'Nagybánhegyes': '2.0', 'Murony': '1.8',
    'Mezőkovácsháza': '2.0', 'Mezőhegyes': '2.0', 'Mezőgyán': '2.0', 'Mezőberény': '1.9', 'Méhkerék': '2.0',
    'Medgyesegyháza': '2.0', 'Medgyesbodzás': '2.0', 'Magyardombegyház': '1.0', 'Magyarbánhegyes': '1.4',
    'Lőkösháza': '1.5', 'Kunágota': '2.0', 'Kötegyán': '2.0', 'Körösújfalu': '2.0', 'Köröstarcsa': '1.8',
    'Körösnagyharsány': '2.0', 'Körösladány': '2.0', 'Kondoros': '2.0', 'Kisdombegyház': '1.4',
    'Kevermes': '1.5', 'Kétsoprony': '1.7', 'Kétegyháza': '2.0', 'Kertészsziget': '2.0', 'Kaszaper': '1.4',
    'Kardoskút': '2.0', 'Kardos': '1.7', 'Kamut': '1.7', 'Hunya': '1.2', 'Gyula': '2.0',
    'Gyomaendrőd': '1.9', 'Geszt': '2.0', 'Gerendás': '1.5', 'Gádoros': '2.0', 'Füzesgyarmat': '2.0',
    'Elek': '1.5', 'Ecsegfalva': '2.0', 'Dombiratos': '1.6', 'Dombegyház': '1.8', 'Doboz': '1.8',
    'Dévaványa': '2.0', 'Csorvás': '1.7', 'Csárdaszállás': '1.8', 'Csanádapáca': '1.4',
    'Csabaszabadi': '2.0', 'Csabacsűd': '2.0', 'Bucsa': '2.0', 'Biharugra': '2.0', 'Bélmegyer': '2.0',
    'Békésszentandrás': '1.7', 'Békéssámson': '1.9', 'Békéscsaba': '2.0', 'Békés': '2.0', 'Battonya': '2.0',
    'Almáskamarás': '2.0', 'Zsana': '2.0', 'Vaskút': '2.0', 'Városföld': '2.0', 'Uszód': '1.0',
    'Újtelek': '2.0', 'Újsolt': '0.0', 'Tompa': '1.7', 'Tiszaug': '1.5', 'Tiszakécske': '2.0',
    'Tiszaalpár': '1.6', 'Tázlár': '0.8', 'Tataháza': '1.7', 'Tass': '2.0', 'Tabdi': '2.0',
    'Szeremle': '1.5', 'Szentkirály': '1.8', 'Szank': '2.0', 'Szalkszentmárton': '2.0', 'Szakmár': '2.0',
    'Szabadszállás': '1.7', 'Sükösd': '1.8', 'Soltvadkert': '1.8', 'Soltszentimre': '1.5', 'Solt': '2.0',
    'Rém': '1.6', 'Pirtó': '1.4', 'Petőfiszállás': '2.0', 'Pálmonostora': '1.8', 'Páhi': '1.0',
    'Öregcsertő': '2.0', 'Orgovány': '1.4', 'Ordas': '1.5', 'Nyárlőrinc': '2.0', 'Nemesnádudvar': '2.0',
    'Nagybaracska': '2.0', 'Móricgát': '1.4', 'Miske': '1.0', 'Mélykút': '2.0', 'Mátételke': '1.7',
    'Madaras': '1.8', 'Lakitelek': '1.9', 'Lajosmizse': '1.6', 'Ladánybene': '1.5', 'Kunszentmiklós': '2.0',
    'Kunszállás': '2.0', 'Kunpeszér': '2.0', 'Kunfehértó': '2.0', 'Kunbaracs': '1.4', 'Kunbaja': '1.4',
    'Kunadacs': '1.6', 'Kömpöc': '1.0', 'Kisszállás': '2.0', 'Kiskunmajsa': '2.0', 'Kiskunhalas': '1.9',
    'Kiskunfélegyháza': '2.0', 'Kiskőrös': '2.0', 'Kerekegyháza': '1.6', 'Kéleshalom': '1.3',
    'Kelebia': '2.0', 'Kecskemét': '1.8', 'Kecel': '2.0', 'Katymár': '2.0', 'Kaskantyú': '1.5',
    'Kalocsa': '2.0', 'Jászszentlászló': '1.8', 'Jánoshalma': '1.8', 'Jakabszállás': '1.5', 'Izsák': '1.7',
    'Imrehegy': '1.5', 'Homokmégy': '1.5', 'Hercegszántó': '2.0', 'Helvécia': '1.4', 'Harta': '2.0',
    'Harkakötöny': '2.0', 'Hajós': '1.5', 'Géderlak': '1.5', 'Gátér': '1.8', 'Gara': '2.0',
    'Fülöpszállás': '1.5', 'Fülöpjakab': '1.0', 'Fülöpháza': '2.0', 'Foktő': '1.5', 'Felsőszentiván': '2.0',
    'Felsőlajos': '1.5', 'Fajsz': '1.5', 'Érsekhalma': '2.0', 'Érsekcsanád': '1.5', 'Dusnok': '1.8',
    'Dunavecse': '2.0', 'Dunatetétlen': '1.5', 'Dunaszentbenedek': '0.0', 'Dunapataj': '2.0',
    'Dunafalva': '1.5', 'Dunaegyháza': '1.7', 'Drágszél': '1.5', 'Dávod': '1.8', 'Csólyospálos': '1.6',
    'Csikéria': '2.0', 'Csengőd': '1.7', 'Csávoly': '1.8', 'Csátalja': '1.7', 'Császártöltés': '2.0',
    'Bugacpusztaháza': '1.9', 'Bugac': '1.9', 'Borota': '1.4', 'Bócsa': '1.8', 'Bátya': '1.5',
    'Bátmonostor': '1.8', 'Balotaszállás': '2.0', 'Ballószög': '1.5', 'Baja': '2.0', 'Bácsszőlős': '2.0',
    'Bácsszentgyörgy': '2.0', 'Bácsborsód': '2.0', 'Bácsbokod': '2.0', 'Bácsalmás': '2.0', 'Apostag': '2.0',
    'Akasztó': '1.5', 'Ágasegyháza': '2.0', 'Zók': '2.0', 'Zengővárkony': '0.0', 'Zaláta': '0.5',
    'Zádor': '1.5', 'Vokány': '2.0', 'Villánykövesd': '2.0', 'Villány': '2.0', 'Versend': '2.0',
    'Véménd': '1.4', 'Velény': '1.7', 'Vékény': '0.0', 'Vejti': '1.5', 'Vázsnok': '1.7',
    'Vásárosdombó': '1.0', 'Vásárosbéc': '0.0', 'Varga': '1.5', 'Várad': '2.0', 'Vajszló': '1.4',
    'Újpetre': '1.5', 'Udvar': '1.5', 'Túrony': '1.0', 'Töttös': '1.6', 'Tótszentgyörgy': '0.0',
    'Tormás': '2.0', 'Tófű': '0.0', 'Téseny': '2.0', 'Tésenfa': '0.0', 'Tengeri': '0.0', 'Teklafalu': '2.0',
    'Tékes': '1.0', 'Tarrós': '1.0', 'Szűr': '2.0', 'Szulimán': '0.0', 'Szörény': '2.0', 'Szőkéd': '0.0',
    'Szőke': '2.0', 'Szilvás': '1.5', 'Szilágy': '1.2', 'Szigetvár': '2.0', 'Szentlőrinc': '1.8',
    'Szentlászló': '1.5', 'Szentkatalin': '1.0', 'Szentegát': '2.0', 'Szentdénes': '1.4', 'Szemely': '2.0',
    'Szellő': '2.0', 'Székelyszabar': '2.0', 'Szederkény': '2.0', 'Szebény': '2.0', 'Szava': '1.5',
    'Szászvár': '1.5', 'Szárász': '0.0', 'Szaporca': '1.5', 'Szalatnak': '1.0', 'Szalánta': '1.5',
    'Szajk': '1.6', 'Szágy': '2.0', 'Szabadszentkirály': '1.7', 'Sumony': '2.0', 'Sósvertike': '2.0',
    'Somogyviszló': '0.0', 'Somogyhatvan': '2.0', 'Somogyhárságy': '2.0', 'Somogyapáti': '2.0',
    'Somberek': '1.8', 'Siklósnagyfalu': '2.0', 'Siklósbodony': '2.0', 'Siklós': '2.0', 'Sellye': '2.0',
    'Sátorhely': '2.0', 'Sásd': '1.8', 'Sárok': '2.0', 'Sámod': '0.0', 'Rózsafa': '1.4', 'Romonya': '0.0',
    'Rádfalva': '1.2', 'Pogány': '1.5', 'Pócsa': '2.0', 'Piskó': '1.4', 'Pettend': '0.0', 'Peterd': '0.5',
    'Pereked': '0.0', 'Pellérd': '2.0', 'Pécsvárad': '2.0', 'Pécsudvard': '2.0', 'Pécsdevecser': '0.0',
    'Pécsbagota': '2.0', 'Pécs': '2.0', 'Patapoklosi': '0.0', 'Páprád': '2.0', 'Palotabozsok': '1.4',
    'Palkonya': '1.1', 'Palé': '2.0', 'Ózdfalu': '0.0', 'Oroszló': '2.0', 'Orfű': '2.0', 'Old': '2.0',
    'Olasz': '1.5', 'Okorvölgy': '0.6', 'Okorág': '1.4', 'Ófalu': '1.0', 'Óbánya': '1.3',
    'Nyugotszenterzsébet': '0.0', 'Nemeske': '1.5', 'Nagyváty': '0.0', 'Nagytótfalu': '1.0',
    'Nagypeterd': '0.0', 'Nagypall': '2.0', 'Nagynyárád': '1.5', 'Nagykozár': '2.0', 'Nagyharsány': '2.0',
    'Nagyhajmás': '1.0', 'Nagydobsza': '0.0', 'Nagycsány': '2.0', 'Nagybudmér': '1.5', 'Mozsgó': '1.5',
    'Monyoród': '2.0', 'Molvány': '0.0', 'Mindszentgodisa': '1.5', 'Meződ': '2.0', 'Merenye': '1.5',
    'Mekényes': '1.0', 'Mecsekpölöske': '1.4', 'Mecseknádasd': '1.7', 'Máza': '1.0', 'Matty': '1.0',
    'Martonfa': '0.0', 'Márok': '2.0', 'Marócsa': '2.0', 'Markóc': '1.4', 'Máriakéménd': '2.0',
    'Márfa': '0.0', 'Maráza': '2.0', 'Mánfa': '2.0', 'Majs': '2.0', 'Magyartelek': '1.0',
    'Magyarszék': '1.4', 'Magyarsarlós': '2.0', 'Magyarmecske': '0.5', 'Magyarlukafa': '1.0',
    'Magyarhertelend': '2.0', 'Magyaregregy': '0.0', 'Magyarbóly': '2.0', 'Mágocs': '1.5', 'Lúzsok': '1.5',
    'Lovászhetény': '1.2', 'Lothárd': '2.0', 'Liptód': '1.7', 'Lippó': '2.0', 'Liget': '1.5',
    'Lapáncsa': '2.0', 'Lánycsók': '2.0', 'Kővágótöttös': '1.0', 'Kővágószőlős': '1.4', 'Kölked': '1.4',
    'Kökény': '1.5', 'Köblény': '1.0', 'Kozármisleny': '1.6', 'Kovácsszénája': '0.0', 'Kovácshida': '1.5',
    'Kórós': '2.0', 'Komló': '2.0', 'Kisszentmárton': '0.2', 'Kisvaszar': '1.0', 'Kistótfalu': '2.0',
    'Kistapolca': '2.0', 'Kistamási': '0.0', 'Kisnyárád': '2.0', 'Kislippó': '2.0', 'Kiskassa': '0.0',
    'Kisjakabfalva': '1.0', 'Kisherend': '0.6', 'Kisharsány': '2.0', 'Kishajmás': '2.0', 'Kisdobsza': '1.0',
    'Kisdér': '0.0', 'Kisbudmér': '1.7', 'Kisbeszterce': '2.0', 'Kisasszonyfa': '0.5',
    'Királyegyháza': '1.8', 'Kétújfalu': '2.0', 'Keszü': '1.0', 'Kemse': '0.0', 'Kémes': '1.5',
    'Kékesd': '2.0', 'Kátoly': '1.5', 'Katádfa': '0.5', 'Kásád': '2.0', 'Kárász': '1.0', 'Kákics': '2.0',
    'Kacsóta': '0.8', 'Ivándárda': '2.0', 'Ivánbattyán': '2.0', 'Ipacsfa': '1.5', 'Illocska': '2.0',
    'Ibafa': '0.0', 'Husztót': '0.0', 'Hosszúhetény': '2.0', 'Horváthertelend': '0.0', 'Homorúd': '2.0',
    'Hobol': '1.5', 'Hirics': '1.5', 'Himesháza': '2.0', 'Hidas': '1.7', 'Hetvehely': '1.0',
    'Helesfa': '0.0', 'Hegyszentmárton': '0.0', 'Hegyhátmaróc': '2.0', 'Hásságy': '1.0', 'Harkány': '2.0',
    'Gyöngyösmellék': '2.0', 'Gyöngyfa': '2.0', 'Gyód': '1.0', 'Görcsönydoboka': '1.8', 'Görcsöny': '2.0',
    'Gödre': '2.0', 'Gordisa': '1.5', 'Gilvánfa': '1.5', 'Geresdlak': '1.5', 'Gerényes': '1.0',
    'Gerde': '2.0', 'Garé': '2.0', 'Felsőszentmárton': '1.3', 'Felsőegerszeg': '1.6', 'Feked': '0.0',
    'Fazekasboda': '2.0', 'Erzsébet': '2.0', 'Erdősmecske': '2.0', 'Erdősmárok': '2.0', 'Endrőc': '2.0',
    'Ellend': '1.2', 'Egyházaskozár': '1.5', 'Egyházasharaszti': '2.0', 'Egerág': '1.4',
    'Dunaszekcső': '2.0', 'Drávasztára': '1.0', 'Drávaszerdahely': '2.0', 'Drávaszabolcs': '1.7',
    'Drávapiski': '0.0', 'Drávapalkonya': '1.5', 'Drávakeresztúr': '2.0', 'Drávaiványi': '2.0',
    'Drávafok': '0.5', 'Drávacsepely': '1.5', 'Drávacsehi': '1.5', 'Diósviszló': '1.2', 'Dinnyeberki': '1.0',
    'Dencsháza': '2.0', 'Csonkamindszent': '1.5', 'Csertő': '2.0', 'Cserkút': '1.4', 'Cserdi': '1.0',
    'Csebény': '0.0', 'Csarnóta': '1.0', 'Csányoszró': '1.0', 'Cún': '0.0', 'Bürüs': '2.0', 'Bükkösd': '1.7',
    'Botykapeterd': '0.0', 'Bosta': '1.5', 'Borjád': '2.0', 'Bóly': '2.0', 'Boldogasszonyfa': '1.0',
    'Bogdása': '1.0', 'Bogádmindszent': '0.0', 'Bogád': '2.0', 'Bodolyabér': '2.0', 'Boda': '1.5',
    'Bisse': '2.0', 'Birján': '2.0', 'Bikal': '1.0', 'Bicsérd': '2.0', 'Bezedek': '2.0', 'Besence': '1.0',
    'Berkesd': '1.2', 'Beremend': '2.0', 'Belvárdgyula': '2.0', 'Basal': '0.0', 'Baranyaszentgyörgy': '2.0',
    'Baranyajenő': '2.0', 'Baranyahídvég': '0.0', 'Bár': '2.0', 'Bánfa': '0.5', 'Baksa': '2.0',
    'Bakonya': '1.2', 'Bakóca': '1.5', 'Babarcszőlős': '1.5', 'Babarc': '2.0', 'Áta': '0.0',
    'Aranyosgadány': '0.0', 'Apátvarasd': '2.0', 'Alsószentmárton': '2.0', 'Alsómocsolád': '2.0',
    'Almáskeresztúr': '0.0', 'Almamellék': '0.0', 'Ág': '1.0', 'Adorjás': '0.0', 'Abaliget': '2.0',
    'Budapest': '2.0'
}
